# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' BalanceSheet Class
#'
#' @field assets 
#' @field tangibleAssets 
#' @field currentAssets 
#' @field cashAndCashEquivalents 
#' @field cashAndShortTermInvestments 
#' @field inventory 
#' @field currentNetReceivables 
#' @field nonCurrentAssets 
#' @field propertyPlantEquipment 
#' @field accumulatedDepreciationAmortization 
#' @field intangibleAssets 
#' @field intangibleAssetsExcludingGoodwill 
#' @field goodwill 
#' @field investments 
#' @field longTermInvestments 
#' @field shortTermInvestments 
#' @field otherCurrentAssets 
#' @field otherNonCurrentAssets 
#' @field liabilities 
#' @field currentLiabilities 
#' @field currentAccountsPayable 
#' @field deferredRevenue 
#' @field currentDebt 
#' @field shortTermDebt 
#' @field nonCurrentLiabilities 
#' @field capitalLeaseObligations 
#' @field longTermDebt 
#' @field currentLongTermDebt 
#' @field longTermDebtNonCurrent 
#' @field shortLongTermDebtTotal 
#' @field otherCurrentLiabilities 
#' @field otherNonCurrentLiabilities 
#' @field equity 
#' @field treasuryStock 
#' @field retainedEarnings 
#' @field commonStock 
#' @field sharesOutstanding 
#' @field accumulatedOtherComprehensiveIncome 
#' @field workingCapital 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BalanceSheet <- R6::R6Class(
  'BalanceSheet',
  public = list(
    `assets` = NULL,
    `tangibleAssets` = NULL,
    `currentAssets` = NULL,
    `cashAndCashEquivalents` = NULL,
    `cashAndShortTermInvestments` = NULL,
    `inventory` = NULL,
    `currentNetReceivables` = NULL,
    `nonCurrentAssets` = NULL,
    `propertyPlantEquipment` = NULL,
    `accumulatedDepreciationAmortization` = NULL,
    `intangibleAssets` = NULL,
    `intangibleAssetsExcludingGoodwill` = NULL,
    `goodwill` = NULL,
    `investments` = NULL,
    `longTermInvestments` = NULL,
    `shortTermInvestments` = NULL,
    `otherCurrentAssets` = NULL,
    `otherNonCurrentAssets` = NULL,
    `liabilities` = NULL,
    `currentLiabilities` = NULL,
    `currentAccountsPayable` = NULL,
    `deferredRevenue` = NULL,
    `currentDebt` = NULL,
    `shortTermDebt` = NULL,
    `nonCurrentLiabilities` = NULL,
    `capitalLeaseObligations` = NULL,
    `longTermDebt` = NULL,
    `currentLongTermDebt` = NULL,
    `longTermDebtNonCurrent` = NULL,
    `shortLongTermDebtTotal` = NULL,
    `otherCurrentLiabilities` = NULL,
    `otherNonCurrentLiabilities` = NULL,
    `equity` = NULL,
    `treasuryStock` = NULL,
    `retainedEarnings` = NULL,
    `commonStock` = NULL,
    `sharesOutstanding` = NULL,
    `accumulatedOtherComprehensiveIncome` = NULL,
    `workingCapital` = NULL,
    initialize = function(`assets`, `tangibleAssets`, `currentAssets`, `cashAndCashEquivalents`, `cashAndShortTermInvestments`, `inventory`, `currentNetReceivables`, `nonCurrentAssets`, `propertyPlantEquipment`, `accumulatedDepreciationAmortization`, `intangibleAssets`, `intangibleAssetsExcludingGoodwill`, `goodwill`, `investments`, `longTermInvestments`, `shortTermInvestments`, `otherCurrentAssets`, `otherNonCurrentAssets`, `liabilities`, `currentLiabilities`, `currentAccountsPayable`, `deferredRevenue`, `currentDebt`, `shortTermDebt`, `nonCurrentLiabilities`, `capitalLeaseObligations`, `longTermDebt`, `currentLongTermDebt`, `longTermDebtNonCurrent`, `shortLongTermDebtTotal`, `otherCurrentLiabilities`, `otherNonCurrentLiabilities`, `equity`, `treasuryStock`, `retainedEarnings`, `commonStock`, `sharesOutstanding`, `accumulatedOtherComprehensiveIncome`, `workingCapital`){
      if (!missing(`assets`)) {
        stopifnot(is.numeric(`assets`), length(`assets`) == 1)
        self$`assets` <- `assets`
      }
      if (!missing(`tangibleAssets`)) {
        stopifnot(is.numeric(`tangibleAssets`), length(`tangibleAssets`) == 1)
        self$`tangibleAssets` <- `tangibleAssets`
      }
      if (!missing(`currentAssets`)) {
        stopifnot(is.numeric(`currentAssets`), length(`currentAssets`) == 1)
        self$`currentAssets` <- `currentAssets`
      }
      if (!missing(`cashAndCashEquivalents`)) {
        stopifnot(is.numeric(`cashAndCashEquivalents`), length(`cashAndCashEquivalents`) == 1)
        self$`cashAndCashEquivalents` <- `cashAndCashEquivalents`
      }
      if (!missing(`cashAndShortTermInvestments`)) {
        stopifnot(is.numeric(`cashAndShortTermInvestments`), length(`cashAndShortTermInvestments`) == 1)
        self$`cashAndShortTermInvestments` <- `cashAndShortTermInvestments`
      }
      if (!missing(`inventory`)) {
        stopifnot(is.numeric(`inventory`), length(`inventory`) == 1)
        self$`inventory` <- `inventory`
      }
      if (!missing(`currentNetReceivables`)) {
        stopifnot(is.numeric(`currentNetReceivables`), length(`currentNetReceivables`) == 1)
        self$`currentNetReceivables` <- `currentNetReceivables`
      }
      if (!missing(`nonCurrentAssets`)) {
        stopifnot(is.numeric(`nonCurrentAssets`), length(`nonCurrentAssets`) == 1)
        self$`nonCurrentAssets` <- `nonCurrentAssets`
      }
      if (!missing(`propertyPlantEquipment`)) {
        stopifnot(is.numeric(`propertyPlantEquipment`), length(`propertyPlantEquipment`) == 1)
        self$`propertyPlantEquipment` <- `propertyPlantEquipment`
      }
      if (!missing(`accumulatedDepreciationAmortization`)) {
        stopifnot(is.numeric(`accumulatedDepreciationAmortization`), length(`accumulatedDepreciationAmortization`) == 1)
        self$`accumulatedDepreciationAmortization` <- `accumulatedDepreciationAmortization`
      }
      if (!missing(`intangibleAssets`)) {
        stopifnot(is.numeric(`intangibleAssets`), length(`intangibleAssets`) == 1)
        self$`intangibleAssets` <- `intangibleAssets`
      }
      if (!missing(`intangibleAssetsExcludingGoodwill`)) {
        stopifnot(is.numeric(`intangibleAssetsExcludingGoodwill`), length(`intangibleAssetsExcludingGoodwill`) == 1)
        self$`intangibleAssetsExcludingGoodwill` <- `intangibleAssetsExcludingGoodwill`
      }
      if (!missing(`goodwill`)) {
        stopifnot(is.numeric(`goodwill`), length(`goodwill`) == 1)
        self$`goodwill` <- `goodwill`
      }
      if (!missing(`investments`)) {
        stopifnot(is.numeric(`investments`), length(`investments`) == 1)
        self$`investments` <- `investments`
      }
      if (!missing(`longTermInvestments`)) {
        stopifnot(is.numeric(`longTermInvestments`), length(`longTermInvestments`) == 1)
        self$`longTermInvestments` <- `longTermInvestments`
      }
      if (!missing(`shortTermInvestments`)) {
        stopifnot(is.numeric(`shortTermInvestments`), length(`shortTermInvestments`) == 1)
        self$`shortTermInvestments` <- `shortTermInvestments`
      }
      if (!missing(`otherCurrentAssets`)) {
        stopifnot(is.numeric(`otherCurrentAssets`), length(`otherCurrentAssets`) == 1)
        self$`otherCurrentAssets` <- `otherCurrentAssets`
      }
      if (!missing(`otherNonCurrentAssets`)) {
        stopifnot(is.numeric(`otherNonCurrentAssets`), length(`otherNonCurrentAssets`) == 1)
        self$`otherNonCurrentAssets` <- `otherNonCurrentAssets`
      }
      if (!missing(`liabilities`)) {
        stopifnot(is.numeric(`liabilities`), length(`liabilities`) == 1)
        self$`liabilities` <- `liabilities`
      }
      if (!missing(`currentLiabilities`)) {
        stopifnot(is.numeric(`currentLiabilities`), length(`currentLiabilities`) == 1)
        self$`currentLiabilities` <- `currentLiabilities`
      }
      if (!missing(`currentAccountsPayable`)) {
        stopifnot(is.numeric(`currentAccountsPayable`), length(`currentAccountsPayable`) == 1)
        self$`currentAccountsPayable` <- `currentAccountsPayable`
      }
      if (!missing(`deferredRevenue`)) {
        stopifnot(is.numeric(`deferredRevenue`), length(`deferredRevenue`) == 1)
        self$`deferredRevenue` <- `deferredRevenue`
      }
      if (!missing(`currentDebt`)) {
        stopifnot(is.numeric(`currentDebt`), length(`currentDebt`) == 1)
        self$`currentDebt` <- `currentDebt`
      }
      if (!missing(`shortTermDebt`)) {
        stopifnot(is.numeric(`shortTermDebt`), length(`shortTermDebt`) == 1)
        self$`shortTermDebt` <- `shortTermDebt`
      }
      if (!missing(`nonCurrentLiabilities`)) {
        stopifnot(is.numeric(`nonCurrentLiabilities`), length(`nonCurrentLiabilities`) == 1)
        self$`nonCurrentLiabilities` <- `nonCurrentLiabilities`
      }
      if (!missing(`capitalLeaseObligations`)) {
        stopifnot(is.numeric(`capitalLeaseObligations`), length(`capitalLeaseObligations`) == 1)
        self$`capitalLeaseObligations` <- `capitalLeaseObligations`
      }
      if (!missing(`longTermDebt`)) {
        stopifnot(is.numeric(`longTermDebt`), length(`longTermDebt`) == 1)
        self$`longTermDebt` <- `longTermDebt`
      }
      if (!missing(`currentLongTermDebt`)) {
        stopifnot(is.numeric(`currentLongTermDebt`), length(`currentLongTermDebt`) == 1)
        self$`currentLongTermDebt` <- `currentLongTermDebt`
      }
      if (!missing(`longTermDebtNonCurrent`)) {
        stopifnot(is.numeric(`longTermDebtNonCurrent`), length(`longTermDebtNonCurrent`) == 1)
        self$`longTermDebtNonCurrent` <- `longTermDebtNonCurrent`
      }
      if (!missing(`shortLongTermDebtTotal`)) {
        stopifnot(is.numeric(`shortLongTermDebtTotal`), length(`shortLongTermDebtTotal`) == 1)
        self$`shortLongTermDebtTotal` <- `shortLongTermDebtTotal`
      }
      if (!missing(`otherCurrentLiabilities`)) {
        stopifnot(is.numeric(`otherCurrentLiabilities`), length(`otherCurrentLiabilities`) == 1)
        self$`otherCurrentLiabilities` <- `otherCurrentLiabilities`
      }
      if (!missing(`otherNonCurrentLiabilities`)) {
        stopifnot(is.numeric(`otherNonCurrentLiabilities`), length(`otherNonCurrentLiabilities`) == 1)
        self$`otherNonCurrentLiabilities` <- `otherNonCurrentLiabilities`
      }
      if (!missing(`equity`)) {
        stopifnot(is.numeric(`equity`), length(`equity`) == 1)
        self$`equity` <- `equity`
      }
      if (!missing(`treasuryStock`)) {
        stopifnot(is.numeric(`treasuryStock`), length(`treasuryStock`) == 1)
        self$`treasuryStock` <- `treasuryStock`
      }
      if (!missing(`retainedEarnings`)) {
        stopifnot(is.numeric(`retainedEarnings`), length(`retainedEarnings`) == 1)
        self$`retainedEarnings` <- `retainedEarnings`
      }
      if (!missing(`commonStock`)) {
        stopifnot(is.numeric(`commonStock`), length(`commonStock`) == 1)
        self$`commonStock` <- `commonStock`
      }
      if (!missing(`sharesOutstanding`)) {
        stopifnot(is.numeric(`sharesOutstanding`), length(`sharesOutstanding`) == 1)
        self$`sharesOutstanding` <- `sharesOutstanding`
      }
      if (!missing(`accumulatedOtherComprehensiveIncome`)) {
        stopifnot(is.numeric(`accumulatedOtherComprehensiveIncome`), length(`accumulatedOtherComprehensiveIncome`) == 1)
        self$`accumulatedOtherComprehensiveIncome` <- `accumulatedOtherComprehensiveIncome`
      }
      if (!missing(`workingCapital`)) {
        stopifnot(is.numeric(`workingCapital`), length(`workingCapital`) == 1)
        self$`workingCapital` <- `workingCapital`
      }
    },
    toJSON = function() {
      BalanceSheetObject <- list()
      if (!is.null(self$`assets`)) {
        BalanceSheetObject[['assets']] <- self$`assets`
      }
      if (!is.null(self$`tangibleAssets`)) {
        BalanceSheetObject[['tangibleAssets']] <- self$`tangibleAssets`
      }
      if (!is.null(self$`currentAssets`)) {
        BalanceSheetObject[['currentAssets']] <- self$`currentAssets`
      }
      if (!is.null(self$`cashAndCashEquivalents`)) {
        BalanceSheetObject[['cashAndCashEquivalents']] <- self$`cashAndCashEquivalents`
      }
      if (!is.null(self$`cashAndShortTermInvestments`)) {
        BalanceSheetObject[['cashAndShortTermInvestments']] <- self$`cashAndShortTermInvestments`
      }
      if (!is.null(self$`inventory`)) {
        BalanceSheetObject[['inventory']] <- self$`inventory`
      }
      if (!is.null(self$`currentNetReceivables`)) {
        BalanceSheetObject[['currentNetReceivables']] <- self$`currentNetReceivables`
      }
      if (!is.null(self$`nonCurrentAssets`)) {
        BalanceSheetObject[['nonCurrentAssets']] <- self$`nonCurrentAssets`
      }
      if (!is.null(self$`propertyPlantEquipment`)) {
        BalanceSheetObject[['propertyPlantEquipment']] <- self$`propertyPlantEquipment`
      }
      if (!is.null(self$`accumulatedDepreciationAmortization`)) {
        BalanceSheetObject[['accumulatedDepreciationAmortization']] <- self$`accumulatedDepreciationAmortization`
      }
      if (!is.null(self$`intangibleAssets`)) {
        BalanceSheetObject[['intangibleAssets']] <- self$`intangibleAssets`
      }
      if (!is.null(self$`intangibleAssetsExcludingGoodwill`)) {
        BalanceSheetObject[['intangibleAssetsExcludingGoodwill']] <- self$`intangibleAssetsExcludingGoodwill`
      }
      if (!is.null(self$`goodwill`)) {
        BalanceSheetObject[['goodwill']] <- self$`goodwill`
      }
      if (!is.null(self$`investments`)) {
        BalanceSheetObject[['investments']] <- self$`investments`
      }
      if (!is.null(self$`longTermInvestments`)) {
        BalanceSheetObject[['longTermInvestments']] <- self$`longTermInvestments`
      }
      if (!is.null(self$`shortTermInvestments`)) {
        BalanceSheetObject[['shortTermInvestments']] <- self$`shortTermInvestments`
      }
      if (!is.null(self$`otherCurrentAssets`)) {
        BalanceSheetObject[['otherCurrentAssets']] <- self$`otherCurrentAssets`
      }
      if (!is.null(self$`otherNonCurrentAssets`)) {
        BalanceSheetObject[['otherNonCurrentAssets']] <- self$`otherNonCurrentAssets`
      }
      if (!is.null(self$`liabilities`)) {
        BalanceSheetObject[['liabilities']] <- self$`liabilities`
      }
      if (!is.null(self$`currentLiabilities`)) {
        BalanceSheetObject[['currentLiabilities']] <- self$`currentLiabilities`
      }
      if (!is.null(self$`currentAccountsPayable`)) {
        BalanceSheetObject[['currentAccountsPayable']] <- self$`currentAccountsPayable`
      }
      if (!is.null(self$`deferredRevenue`)) {
        BalanceSheetObject[['deferredRevenue']] <- self$`deferredRevenue`
      }
      if (!is.null(self$`currentDebt`)) {
        BalanceSheetObject[['currentDebt']] <- self$`currentDebt`
      }
      if (!is.null(self$`shortTermDebt`)) {
        BalanceSheetObject[['shortTermDebt']] <- self$`shortTermDebt`
      }
      if (!is.null(self$`nonCurrentLiabilities`)) {
        BalanceSheetObject[['nonCurrentLiabilities']] <- self$`nonCurrentLiabilities`
      }
      if (!is.null(self$`capitalLeaseObligations`)) {
        BalanceSheetObject[['capitalLeaseObligations']] <- self$`capitalLeaseObligations`
      }
      if (!is.null(self$`longTermDebt`)) {
        BalanceSheetObject[['longTermDebt']] <- self$`longTermDebt`
      }
      if (!is.null(self$`currentLongTermDebt`)) {
        BalanceSheetObject[['currentLongTermDebt']] <- self$`currentLongTermDebt`
      }
      if (!is.null(self$`longTermDebtNonCurrent`)) {
        BalanceSheetObject[['longTermDebtNonCurrent']] <- self$`longTermDebtNonCurrent`
      }
      if (!is.null(self$`shortLongTermDebtTotal`)) {
        BalanceSheetObject[['shortLongTermDebtTotal']] <- self$`shortLongTermDebtTotal`
      }
      if (!is.null(self$`otherCurrentLiabilities`)) {
        BalanceSheetObject[['otherCurrentLiabilities']] <- self$`otherCurrentLiabilities`
      }
      if (!is.null(self$`otherNonCurrentLiabilities`)) {
        BalanceSheetObject[['otherNonCurrentLiabilities']] <- self$`otherNonCurrentLiabilities`
      }
      if (!is.null(self$`equity`)) {
        BalanceSheetObject[['equity']] <- self$`equity`
      }
      if (!is.null(self$`treasuryStock`)) {
        BalanceSheetObject[['treasuryStock']] <- self$`treasuryStock`
      }
      if (!is.null(self$`retainedEarnings`)) {
        BalanceSheetObject[['retainedEarnings']] <- self$`retainedEarnings`
      }
      if (!is.null(self$`commonStock`)) {
        BalanceSheetObject[['commonStock']] <- self$`commonStock`
      }
      if (!is.null(self$`sharesOutstanding`)) {
        BalanceSheetObject[['sharesOutstanding']] <- self$`sharesOutstanding`
      }
      if (!is.null(self$`accumulatedOtherComprehensiveIncome`)) {
        BalanceSheetObject[['accumulatedOtherComprehensiveIncome']] <- self$`accumulatedOtherComprehensiveIncome`
      }
      if (!is.null(self$`workingCapital`)) {
        BalanceSheetObject[['workingCapital']] <- self$`workingCapital`
      }

      BalanceSheetObject
    },
    fromJSON = function(BalanceSheetJson) {
      BalanceSheetObject <- jsonlite::fromJSON(BalanceSheetJson)
      if (!is.null(BalanceSheetObject$`assets`)) {
        self$`assets` <- BalanceSheetObject$`assets`
      }
      if (!is.null(BalanceSheetObject$`tangibleAssets`)) {
        self$`tangibleAssets` <- BalanceSheetObject$`tangibleAssets`
      }
      if (!is.null(BalanceSheetObject$`currentAssets`)) {
        self$`currentAssets` <- BalanceSheetObject$`currentAssets`
      }
      if (!is.null(BalanceSheetObject$`cashAndCashEquivalents`)) {
        self$`cashAndCashEquivalents` <- BalanceSheetObject$`cashAndCashEquivalents`
      }
      if (!is.null(BalanceSheetObject$`cashAndShortTermInvestments`)) {
        self$`cashAndShortTermInvestments` <- BalanceSheetObject$`cashAndShortTermInvestments`
      }
      if (!is.null(BalanceSheetObject$`inventory`)) {
        self$`inventory` <- BalanceSheetObject$`inventory`
      }
      if (!is.null(BalanceSheetObject$`currentNetReceivables`)) {
        self$`currentNetReceivables` <- BalanceSheetObject$`currentNetReceivables`
      }
      if (!is.null(BalanceSheetObject$`nonCurrentAssets`)) {
        self$`nonCurrentAssets` <- BalanceSheetObject$`nonCurrentAssets`
      }
      if (!is.null(BalanceSheetObject$`propertyPlantEquipment`)) {
        self$`propertyPlantEquipment` <- BalanceSheetObject$`propertyPlantEquipment`
      }
      if (!is.null(BalanceSheetObject$`accumulatedDepreciationAmortization`)) {
        self$`accumulatedDepreciationAmortization` <- BalanceSheetObject$`accumulatedDepreciationAmortization`
      }
      if (!is.null(BalanceSheetObject$`intangibleAssets`)) {
        self$`intangibleAssets` <- BalanceSheetObject$`intangibleAssets`
      }
      if (!is.null(BalanceSheetObject$`intangibleAssetsExcludingGoodwill`)) {
        self$`intangibleAssetsExcludingGoodwill` <- BalanceSheetObject$`intangibleAssetsExcludingGoodwill`
      }
      if (!is.null(BalanceSheetObject$`goodwill`)) {
        self$`goodwill` <- BalanceSheetObject$`goodwill`
      }
      if (!is.null(BalanceSheetObject$`investments`)) {
        self$`investments` <- BalanceSheetObject$`investments`
      }
      if (!is.null(BalanceSheetObject$`longTermInvestments`)) {
        self$`longTermInvestments` <- BalanceSheetObject$`longTermInvestments`
      }
      if (!is.null(BalanceSheetObject$`shortTermInvestments`)) {
        self$`shortTermInvestments` <- BalanceSheetObject$`shortTermInvestments`
      }
      if (!is.null(BalanceSheetObject$`otherCurrentAssets`)) {
        self$`otherCurrentAssets` <- BalanceSheetObject$`otherCurrentAssets`
      }
      if (!is.null(BalanceSheetObject$`otherNonCurrentAssets`)) {
        self$`otherNonCurrentAssets` <- BalanceSheetObject$`otherNonCurrentAssets`
      }
      if (!is.null(BalanceSheetObject$`liabilities`)) {
        self$`liabilities` <- BalanceSheetObject$`liabilities`
      }
      if (!is.null(BalanceSheetObject$`currentLiabilities`)) {
        self$`currentLiabilities` <- BalanceSheetObject$`currentLiabilities`
      }
      if (!is.null(BalanceSheetObject$`currentAccountsPayable`)) {
        self$`currentAccountsPayable` <- BalanceSheetObject$`currentAccountsPayable`
      }
      if (!is.null(BalanceSheetObject$`deferredRevenue`)) {
        self$`deferredRevenue` <- BalanceSheetObject$`deferredRevenue`
      }
      if (!is.null(BalanceSheetObject$`currentDebt`)) {
        self$`currentDebt` <- BalanceSheetObject$`currentDebt`
      }
      if (!is.null(BalanceSheetObject$`shortTermDebt`)) {
        self$`shortTermDebt` <- BalanceSheetObject$`shortTermDebt`
      }
      if (!is.null(BalanceSheetObject$`nonCurrentLiabilities`)) {
        self$`nonCurrentLiabilities` <- BalanceSheetObject$`nonCurrentLiabilities`
      }
      if (!is.null(BalanceSheetObject$`capitalLeaseObligations`)) {
        self$`capitalLeaseObligations` <- BalanceSheetObject$`capitalLeaseObligations`
      }
      if (!is.null(BalanceSheetObject$`longTermDebt`)) {
        self$`longTermDebt` <- BalanceSheetObject$`longTermDebt`
      }
      if (!is.null(BalanceSheetObject$`currentLongTermDebt`)) {
        self$`currentLongTermDebt` <- BalanceSheetObject$`currentLongTermDebt`
      }
      if (!is.null(BalanceSheetObject$`longTermDebtNonCurrent`)) {
        self$`longTermDebtNonCurrent` <- BalanceSheetObject$`longTermDebtNonCurrent`
      }
      if (!is.null(BalanceSheetObject$`shortLongTermDebtTotal`)) {
        self$`shortLongTermDebtTotal` <- BalanceSheetObject$`shortLongTermDebtTotal`
      }
      if (!is.null(BalanceSheetObject$`otherCurrentLiabilities`)) {
        self$`otherCurrentLiabilities` <- BalanceSheetObject$`otherCurrentLiabilities`
      }
      if (!is.null(BalanceSheetObject$`otherNonCurrentLiabilities`)) {
        self$`otherNonCurrentLiabilities` <- BalanceSheetObject$`otherNonCurrentLiabilities`
      }
      if (!is.null(BalanceSheetObject$`equity`)) {
        self$`equity` <- BalanceSheetObject$`equity`
      }
      if (!is.null(BalanceSheetObject$`treasuryStock`)) {
        self$`treasuryStock` <- BalanceSheetObject$`treasuryStock`
      }
      if (!is.null(BalanceSheetObject$`retainedEarnings`)) {
        self$`retainedEarnings` <- BalanceSheetObject$`retainedEarnings`
      }
      if (!is.null(BalanceSheetObject$`commonStock`)) {
        self$`commonStock` <- BalanceSheetObject$`commonStock`
      }
      if (!is.null(BalanceSheetObject$`sharesOutstanding`)) {
        self$`sharesOutstanding` <- BalanceSheetObject$`sharesOutstanding`
      }
      if (!is.null(BalanceSheetObject$`accumulatedOtherComprehensiveIncome`)) {
        self$`accumulatedOtherComprehensiveIncome` <- BalanceSheetObject$`accumulatedOtherComprehensiveIncome`
      }
      if (!is.null(BalanceSheetObject$`workingCapital`)) {
        self$`workingCapital` <- BalanceSheetObject$`workingCapital`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "assets": %d,
           "tangibleAssets": %d,
           "currentAssets": %d,
           "cashAndCashEquivalents": %d,
           "cashAndShortTermInvestments": %d,
           "inventory": %d,
           "currentNetReceivables": %d,
           "nonCurrentAssets": %d,
           "propertyPlantEquipment": %d,
           "accumulatedDepreciationAmortization": %d,
           "intangibleAssets": %d,
           "intangibleAssetsExcludingGoodwill": %d,
           "goodwill": %d,
           "investments": %d,
           "longTermInvestments": %d,
           "shortTermInvestments": %d,
           "otherCurrentAssets": %d,
           "otherNonCurrentAssets": %d,
           "liabilities": %d,
           "currentLiabilities": %d,
           "currentAccountsPayable": %d,
           "deferredRevenue": %d,
           "currentDebt": %d,
           "shortTermDebt": %d,
           "nonCurrentLiabilities": %d,
           "capitalLeaseObligations": %d,
           "longTermDebt": %d,
           "currentLongTermDebt": %d,
           "longTermDebtNonCurrent": %d,
           "shortLongTermDebtTotal": %d,
           "otherCurrentLiabilities": %d,
           "otherNonCurrentLiabilities": %d,
           "equity": %d,
           "treasuryStock": %d,
           "retainedEarnings": %d,
           "commonStock": %d,
           "sharesOutstanding": %d,
           "accumulatedOtherComprehensiveIncome": %d,
           "workingCapital": %d
        }',
        self$`assets`,
        self$`tangibleAssets`,
        self$`currentAssets`,
        self$`cashAndCashEquivalents`,
        self$`cashAndShortTermInvestments`,
        self$`inventory`,
        self$`currentNetReceivables`,
        self$`nonCurrentAssets`,
        self$`propertyPlantEquipment`,
        self$`accumulatedDepreciationAmortization`,
        self$`intangibleAssets`,
        self$`intangibleAssetsExcludingGoodwill`,
        self$`goodwill`,
        self$`investments`,
        self$`longTermInvestments`,
        self$`shortTermInvestments`,
        self$`otherCurrentAssets`,
        self$`otherNonCurrentAssets`,
        self$`liabilities`,
        self$`currentLiabilities`,
        self$`currentAccountsPayable`,
        self$`deferredRevenue`,
        self$`currentDebt`,
        self$`shortTermDebt`,
        self$`nonCurrentLiabilities`,
        self$`capitalLeaseObligations`,
        self$`longTermDebt`,
        self$`currentLongTermDebt`,
        self$`longTermDebtNonCurrent`,
        self$`shortLongTermDebtTotal`,
        self$`otherCurrentLiabilities`,
        self$`otherNonCurrentLiabilities`,
        self$`equity`,
        self$`treasuryStock`,
        self$`retainedEarnings`,
        self$`commonStock`,
        self$`sharesOutstanding`,
        self$`accumulatedOtherComprehensiveIncome`,
        self$`workingCapital`
      )
    },
    fromJSONString = function(BalanceSheetJson) {
      BalanceSheetObject <- jsonlite::fromJSON(BalanceSheetJson)
      self$`assets` <- BalanceSheetObject$`assets`
      self$`tangibleAssets` <- BalanceSheetObject$`tangibleAssets`
      self$`currentAssets` <- BalanceSheetObject$`currentAssets`
      self$`cashAndCashEquivalents` <- BalanceSheetObject$`cashAndCashEquivalents`
      self$`cashAndShortTermInvestments` <- BalanceSheetObject$`cashAndShortTermInvestments`
      self$`inventory` <- BalanceSheetObject$`inventory`
      self$`currentNetReceivables` <- BalanceSheetObject$`currentNetReceivables`
      self$`nonCurrentAssets` <- BalanceSheetObject$`nonCurrentAssets`
      self$`propertyPlantEquipment` <- BalanceSheetObject$`propertyPlantEquipment`
      self$`accumulatedDepreciationAmortization` <- BalanceSheetObject$`accumulatedDepreciationAmortization`
      self$`intangibleAssets` <- BalanceSheetObject$`intangibleAssets`
      self$`intangibleAssetsExcludingGoodwill` <- BalanceSheetObject$`intangibleAssetsExcludingGoodwill`
      self$`goodwill` <- BalanceSheetObject$`goodwill`
      self$`investments` <- BalanceSheetObject$`investments`
      self$`longTermInvestments` <- BalanceSheetObject$`longTermInvestments`
      self$`shortTermInvestments` <- BalanceSheetObject$`shortTermInvestments`
      self$`otherCurrentAssets` <- BalanceSheetObject$`otherCurrentAssets`
      self$`otherNonCurrentAssets` <- BalanceSheetObject$`otherNonCurrentAssets`
      self$`liabilities` <- BalanceSheetObject$`liabilities`
      self$`currentLiabilities` <- BalanceSheetObject$`currentLiabilities`
      self$`currentAccountsPayable` <- BalanceSheetObject$`currentAccountsPayable`
      self$`deferredRevenue` <- BalanceSheetObject$`deferredRevenue`
      self$`currentDebt` <- BalanceSheetObject$`currentDebt`
      self$`shortTermDebt` <- BalanceSheetObject$`shortTermDebt`
      self$`nonCurrentLiabilities` <- BalanceSheetObject$`nonCurrentLiabilities`
      self$`capitalLeaseObligations` <- BalanceSheetObject$`capitalLeaseObligations`
      self$`longTermDebt` <- BalanceSheetObject$`longTermDebt`
      self$`currentLongTermDebt` <- BalanceSheetObject$`currentLongTermDebt`
      self$`longTermDebtNonCurrent` <- BalanceSheetObject$`longTermDebtNonCurrent`
      self$`shortLongTermDebtTotal` <- BalanceSheetObject$`shortLongTermDebtTotal`
      self$`otherCurrentLiabilities` <- BalanceSheetObject$`otherCurrentLiabilities`
      self$`otherNonCurrentLiabilities` <- BalanceSheetObject$`otherNonCurrentLiabilities`
      self$`equity` <- BalanceSheetObject$`equity`
      self$`treasuryStock` <- BalanceSheetObject$`treasuryStock`
      self$`retainedEarnings` <- BalanceSheetObject$`retainedEarnings`
      self$`commonStock` <- BalanceSheetObject$`commonStock`
      self$`sharesOutstanding` <- BalanceSheetObject$`sharesOutstanding`
      self$`accumulatedOtherComprehensiveIncome` <- BalanceSheetObject$`accumulatedOtherComprehensiveIncome`
      self$`workingCapital` <- BalanceSheetObject$`workingCapital`
    }
  )
)
