# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' CashFlowStatement Class
#'
#' @field operatingCashFlow 
#' @field paymentsForOperatingActivities 
#' @field proceedsFromOperatingActivities 
#' @field changeInOperatingLiabilities 
#' @field changeInOperatingAssets 
#' @field depreciationDepletionAndAmortization 
#' @field capitalExpenditures 
#' @field changeInReceivables 
#' @field changeInInventory 
#' @field profitLoss 
#' @field investments 
#' @field cashFlowFromInvestment 
#' @field cashFlowFromFinancing 
#' @field proceedsFromRepaymentsOfShortTermDebt 
#' @field paymentsForRepurchaseOfCommonStock 
#' @field paymentsForRepurchaseOfEquity 
#' @field paymentsForRepurchaseOfPreferredStock 
#' @field dividendPayout 
#' @field dividendPayoutCommonStock 
#' @field dividendPayoutPreferredStock 
#' @field proceedsFromIssuanceOfCommonStock 
#' @field proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet 
#' @field proceedsFromIssuanceOfPreferredStock 
#' @field proceedsFromRepurchaseOfEquity 
#' @field proceedsFromSaleOfTreasuryStock 
#' @field changeInCashAndCashEquivalents 
#' @field changeInExchangeRate 
#' @field netIncome 
#' @field netBorrowings 
#' @field changeInWorkingCapital 
#' @field otherNonCashItems 
#' @field freeCashFlow 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CashFlowStatement <- R6::R6Class(
  'CashFlowStatement',
  public = list(
    `operatingCashFlow` = NULL,
    `paymentsForOperatingActivities` = NULL,
    `proceedsFromOperatingActivities` = NULL,
    `changeInOperatingLiabilities` = NULL,
    `changeInOperatingAssets` = NULL,
    `depreciationDepletionAndAmortization` = NULL,
    `capitalExpenditures` = NULL,
    `changeInReceivables` = NULL,
    `changeInInventory` = NULL,
    `profitLoss` = NULL,
    `investments` = NULL,
    `cashFlowFromInvestment` = NULL,
    `cashFlowFromFinancing` = NULL,
    `proceedsFromRepaymentsOfShortTermDebt` = NULL,
    `paymentsForRepurchaseOfCommonStock` = NULL,
    `paymentsForRepurchaseOfEquity` = NULL,
    `paymentsForRepurchaseOfPreferredStock` = NULL,
    `dividendPayout` = NULL,
    `dividendPayoutCommonStock` = NULL,
    `dividendPayoutPreferredStock` = NULL,
    `proceedsFromIssuanceOfCommonStock` = NULL,
    `proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet` = NULL,
    `proceedsFromIssuanceOfPreferredStock` = NULL,
    `proceedsFromRepurchaseOfEquity` = NULL,
    `proceedsFromSaleOfTreasuryStock` = NULL,
    `changeInCashAndCashEquivalents` = NULL,
    `changeInExchangeRate` = NULL,
    `netIncome` = NULL,
    `netBorrowings` = NULL,
    `changeInWorkingCapital` = NULL,
    `otherNonCashItems` = NULL,
    `freeCashFlow` = NULL,
    initialize = function(`operatingCashFlow`, `paymentsForOperatingActivities`, `proceedsFromOperatingActivities`, `changeInOperatingLiabilities`, `changeInOperatingAssets`, `depreciationDepletionAndAmortization`, `capitalExpenditures`, `changeInReceivables`, `changeInInventory`, `profitLoss`, `investments`, `cashFlowFromInvestment`, `cashFlowFromFinancing`, `proceedsFromRepaymentsOfShortTermDebt`, `paymentsForRepurchaseOfCommonStock`, `paymentsForRepurchaseOfEquity`, `paymentsForRepurchaseOfPreferredStock`, `dividendPayout`, `dividendPayoutCommonStock`, `dividendPayoutPreferredStock`, `proceedsFromIssuanceOfCommonStock`, `proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`, `proceedsFromIssuanceOfPreferredStock`, `proceedsFromRepurchaseOfEquity`, `proceedsFromSaleOfTreasuryStock`, `changeInCashAndCashEquivalents`, `changeInExchangeRate`, `netIncome`, `netBorrowings`, `changeInWorkingCapital`, `otherNonCashItems`, `freeCashFlow`){
      if (!missing(`operatingCashFlow`)) {
        stopifnot(is.numeric(`operatingCashFlow`), length(`operatingCashFlow`) == 1)
        self$`operatingCashFlow` <- `operatingCashFlow`
      }
      if (!missing(`paymentsForOperatingActivities`)) {
        stopifnot(is.numeric(`paymentsForOperatingActivities`), length(`paymentsForOperatingActivities`) == 1)
        self$`paymentsForOperatingActivities` <- `paymentsForOperatingActivities`
      }
      if (!missing(`proceedsFromOperatingActivities`)) {
        stopifnot(is.numeric(`proceedsFromOperatingActivities`), length(`proceedsFromOperatingActivities`) == 1)
        self$`proceedsFromOperatingActivities` <- `proceedsFromOperatingActivities`
      }
      if (!missing(`changeInOperatingLiabilities`)) {
        stopifnot(is.numeric(`changeInOperatingLiabilities`), length(`changeInOperatingLiabilities`) == 1)
        self$`changeInOperatingLiabilities` <- `changeInOperatingLiabilities`
      }
      if (!missing(`changeInOperatingAssets`)) {
        stopifnot(is.numeric(`changeInOperatingAssets`), length(`changeInOperatingAssets`) == 1)
        self$`changeInOperatingAssets` <- `changeInOperatingAssets`
      }
      if (!missing(`depreciationDepletionAndAmortization`)) {
        stopifnot(is.numeric(`depreciationDepletionAndAmortization`), length(`depreciationDepletionAndAmortization`) == 1)
        self$`depreciationDepletionAndAmortization` <- `depreciationDepletionAndAmortization`
      }
      if (!missing(`capitalExpenditures`)) {
        stopifnot(is.numeric(`capitalExpenditures`), length(`capitalExpenditures`) == 1)
        self$`capitalExpenditures` <- `capitalExpenditures`
      }
      if (!missing(`changeInReceivables`)) {
        stopifnot(is.numeric(`changeInReceivables`), length(`changeInReceivables`) == 1)
        self$`changeInReceivables` <- `changeInReceivables`
      }
      if (!missing(`changeInInventory`)) {
        stopifnot(is.numeric(`changeInInventory`), length(`changeInInventory`) == 1)
        self$`changeInInventory` <- `changeInInventory`
      }
      if (!missing(`profitLoss`)) {
        stopifnot(is.numeric(`profitLoss`), length(`profitLoss`) == 1)
        self$`profitLoss` <- `profitLoss`
      }
      if (!missing(`investments`)) {
        stopifnot(is.numeric(`investments`), length(`investments`) == 1)
        self$`investments` <- `investments`
      }
      if (!missing(`cashFlowFromInvestment`)) {
        stopifnot(is.numeric(`cashFlowFromInvestment`), length(`cashFlowFromInvestment`) == 1)
        self$`cashFlowFromInvestment` <- `cashFlowFromInvestment`
      }
      if (!missing(`cashFlowFromFinancing`)) {
        stopifnot(is.numeric(`cashFlowFromFinancing`), length(`cashFlowFromFinancing`) == 1)
        self$`cashFlowFromFinancing` <- `cashFlowFromFinancing`
      }
      if (!missing(`proceedsFromRepaymentsOfShortTermDebt`)) {
        stopifnot(is.numeric(`proceedsFromRepaymentsOfShortTermDebt`), length(`proceedsFromRepaymentsOfShortTermDebt`) == 1)
        self$`proceedsFromRepaymentsOfShortTermDebt` <- `proceedsFromRepaymentsOfShortTermDebt`
      }
      if (!missing(`paymentsForRepurchaseOfCommonStock`)) {
        stopifnot(is.numeric(`paymentsForRepurchaseOfCommonStock`), length(`paymentsForRepurchaseOfCommonStock`) == 1)
        self$`paymentsForRepurchaseOfCommonStock` <- `paymentsForRepurchaseOfCommonStock`
      }
      if (!missing(`paymentsForRepurchaseOfEquity`)) {
        stopifnot(is.numeric(`paymentsForRepurchaseOfEquity`), length(`paymentsForRepurchaseOfEquity`) == 1)
        self$`paymentsForRepurchaseOfEquity` <- `paymentsForRepurchaseOfEquity`
      }
      if (!missing(`paymentsForRepurchaseOfPreferredStock`)) {
        stopifnot(is.numeric(`paymentsForRepurchaseOfPreferredStock`), length(`paymentsForRepurchaseOfPreferredStock`) == 1)
        self$`paymentsForRepurchaseOfPreferredStock` <- `paymentsForRepurchaseOfPreferredStock`
      }
      if (!missing(`dividendPayout`)) {
        stopifnot(is.numeric(`dividendPayout`), length(`dividendPayout`) == 1)
        self$`dividendPayout` <- `dividendPayout`
      }
      if (!missing(`dividendPayoutCommonStock`)) {
        stopifnot(is.numeric(`dividendPayoutCommonStock`), length(`dividendPayoutCommonStock`) == 1)
        self$`dividendPayoutCommonStock` <- `dividendPayoutCommonStock`
      }
      if (!missing(`dividendPayoutPreferredStock`)) {
        stopifnot(is.numeric(`dividendPayoutPreferredStock`), length(`dividendPayoutPreferredStock`) == 1)
        self$`dividendPayoutPreferredStock` <- `dividendPayoutPreferredStock`
      }
      if (!missing(`proceedsFromIssuanceOfCommonStock`)) {
        stopifnot(is.numeric(`proceedsFromIssuanceOfCommonStock`), length(`proceedsFromIssuanceOfCommonStock`) == 1)
        self$`proceedsFromIssuanceOfCommonStock` <- `proceedsFromIssuanceOfCommonStock`
      }
      if (!missing(`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`)) {
        stopifnot(is.numeric(`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`), length(`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`) == 1)
        self$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet` <- `proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`
      }
      if (!missing(`proceedsFromIssuanceOfPreferredStock`)) {
        stopifnot(is.numeric(`proceedsFromIssuanceOfPreferredStock`), length(`proceedsFromIssuanceOfPreferredStock`) == 1)
        self$`proceedsFromIssuanceOfPreferredStock` <- `proceedsFromIssuanceOfPreferredStock`
      }
      if (!missing(`proceedsFromRepurchaseOfEquity`)) {
        stopifnot(is.numeric(`proceedsFromRepurchaseOfEquity`), length(`proceedsFromRepurchaseOfEquity`) == 1)
        self$`proceedsFromRepurchaseOfEquity` <- `proceedsFromRepurchaseOfEquity`
      }
      if (!missing(`proceedsFromSaleOfTreasuryStock`)) {
        stopifnot(is.numeric(`proceedsFromSaleOfTreasuryStock`), length(`proceedsFromSaleOfTreasuryStock`) == 1)
        self$`proceedsFromSaleOfTreasuryStock` <- `proceedsFromSaleOfTreasuryStock`
      }
      if (!missing(`changeInCashAndCashEquivalents`)) {
        stopifnot(is.numeric(`changeInCashAndCashEquivalents`), length(`changeInCashAndCashEquivalents`) == 1)
        self$`changeInCashAndCashEquivalents` <- `changeInCashAndCashEquivalents`
      }
      if (!missing(`changeInExchangeRate`)) {
        stopifnot(is.numeric(`changeInExchangeRate`), length(`changeInExchangeRate`) == 1)
        self$`changeInExchangeRate` <- `changeInExchangeRate`
      }
      if (!missing(`netIncome`)) {
        stopifnot(is.numeric(`netIncome`), length(`netIncome`) == 1)
        self$`netIncome` <- `netIncome`
      }
      if (!missing(`netBorrowings`)) {
        stopifnot(is.numeric(`netBorrowings`), length(`netBorrowings`) == 1)
        self$`netBorrowings` <- `netBorrowings`
      }
      if (!missing(`changeInWorkingCapital`)) {
        stopifnot(is.numeric(`changeInWorkingCapital`), length(`changeInWorkingCapital`) == 1)
        self$`changeInWorkingCapital` <- `changeInWorkingCapital`
      }
      if (!missing(`otherNonCashItems`)) {
        stopifnot(is.numeric(`otherNonCashItems`), length(`otherNonCashItems`) == 1)
        self$`otherNonCashItems` <- `otherNonCashItems`
      }
      if (!missing(`freeCashFlow`)) {
        stopifnot(is.numeric(`freeCashFlow`), length(`freeCashFlow`) == 1)
        self$`freeCashFlow` <- `freeCashFlow`
      }
    },
    toJSON = function() {
      CashFlowStatementObject <- list()
      if (!is.null(self$`operatingCashFlow`)) {
        CashFlowStatementObject[['operatingCashFlow']] <- self$`operatingCashFlow`
      }
      if (!is.null(self$`paymentsForOperatingActivities`)) {
        CashFlowStatementObject[['paymentsForOperatingActivities']] <- self$`paymentsForOperatingActivities`
      }
      if (!is.null(self$`proceedsFromOperatingActivities`)) {
        CashFlowStatementObject[['proceedsFromOperatingActivities']] <- self$`proceedsFromOperatingActivities`
      }
      if (!is.null(self$`changeInOperatingLiabilities`)) {
        CashFlowStatementObject[['changeInOperatingLiabilities']] <- self$`changeInOperatingLiabilities`
      }
      if (!is.null(self$`changeInOperatingAssets`)) {
        CashFlowStatementObject[['changeInOperatingAssets']] <- self$`changeInOperatingAssets`
      }
      if (!is.null(self$`depreciationDepletionAndAmortization`)) {
        CashFlowStatementObject[['depreciationDepletionAndAmortization']] <- self$`depreciationDepletionAndAmortization`
      }
      if (!is.null(self$`capitalExpenditures`)) {
        CashFlowStatementObject[['capitalExpenditures']] <- self$`capitalExpenditures`
      }
      if (!is.null(self$`changeInReceivables`)) {
        CashFlowStatementObject[['changeInReceivables']] <- self$`changeInReceivables`
      }
      if (!is.null(self$`changeInInventory`)) {
        CashFlowStatementObject[['changeInInventory']] <- self$`changeInInventory`
      }
      if (!is.null(self$`profitLoss`)) {
        CashFlowStatementObject[['profitLoss']] <- self$`profitLoss`
      }
      if (!is.null(self$`investments`)) {
        CashFlowStatementObject[['investments']] <- self$`investments`
      }
      if (!is.null(self$`cashFlowFromInvestment`)) {
        CashFlowStatementObject[['cashFlowFromInvestment']] <- self$`cashFlowFromInvestment`
      }
      if (!is.null(self$`cashFlowFromFinancing`)) {
        CashFlowStatementObject[['cashFlowFromFinancing']] <- self$`cashFlowFromFinancing`
      }
      if (!is.null(self$`proceedsFromRepaymentsOfShortTermDebt`)) {
        CashFlowStatementObject[['proceedsFromRepaymentsOfShortTermDebt']] <- self$`proceedsFromRepaymentsOfShortTermDebt`
      }
      if (!is.null(self$`paymentsForRepurchaseOfCommonStock`)) {
        CashFlowStatementObject[['paymentsForRepurchaseOfCommonStock']] <- self$`paymentsForRepurchaseOfCommonStock`
      }
      if (!is.null(self$`paymentsForRepurchaseOfEquity`)) {
        CashFlowStatementObject[['paymentsForRepurchaseOfEquity']] <- self$`paymentsForRepurchaseOfEquity`
      }
      if (!is.null(self$`paymentsForRepurchaseOfPreferredStock`)) {
        CashFlowStatementObject[['paymentsForRepurchaseOfPreferredStock']] <- self$`paymentsForRepurchaseOfPreferredStock`
      }
      if (!is.null(self$`dividendPayout`)) {
        CashFlowStatementObject[['dividendPayout']] <- self$`dividendPayout`
      }
      if (!is.null(self$`dividendPayoutCommonStock`)) {
        CashFlowStatementObject[['dividendPayoutCommonStock']] <- self$`dividendPayoutCommonStock`
      }
      if (!is.null(self$`dividendPayoutPreferredStock`)) {
        CashFlowStatementObject[['dividendPayoutPreferredStock']] <- self$`dividendPayoutPreferredStock`
      }
      if (!is.null(self$`proceedsFromIssuanceOfCommonStock`)) {
        CashFlowStatementObject[['proceedsFromIssuanceOfCommonStock']] <- self$`proceedsFromIssuanceOfCommonStock`
      }
      if (!is.null(self$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`)) {
        CashFlowStatementObject[['proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet']] <- self$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`
      }
      if (!is.null(self$`proceedsFromIssuanceOfPreferredStock`)) {
        CashFlowStatementObject[['proceedsFromIssuanceOfPreferredStock']] <- self$`proceedsFromIssuanceOfPreferredStock`
      }
      if (!is.null(self$`proceedsFromRepurchaseOfEquity`)) {
        CashFlowStatementObject[['proceedsFromRepurchaseOfEquity']] <- self$`proceedsFromRepurchaseOfEquity`
      }
      if (!is.null(self$`proceedsFromSaleOfTreasuryStock`)) {
        CashFlowStatementObject[['proceedsFromSaleOfTreasuryStock']] <- self$`proceedsFromSaleOfTreasuryStock`
      }
      if (!is.null(self$`changeInCashAndCashEquivalents`)) {
        CashFlowStatementObject[['changeInCashAndCashEquivalents']] <- self$`changeInCashAndCashEquivalents`
      }
      if (!is.null(self$`changeInExchangeRate`)) {
        CashFlowStatementObject[['changeInExchangeRate']] <- self$`changeInExchangeRate`
      }
      if (!is.null(self$`netIncome`)) {
        CashFlowStatementObject[['netIncome']] <- self$`netIncome`
      }
      if (!is.null(self$`netBorrowings`)) {
        CashFlowStatementObject[['netBorrowings']] <- self$`netBorrowings`
      }
      if (!is.null(self$`changeInWorkingCapital`)) {
        CashFlowStatementObject[['changeInWorkingCapital']] <- self$`changeInWorkingCapital`
      }
      if (!is.null(self$`otherNonCashItems`)) {
        CashFlowStatementObject[['otherNonCashItems']] <- self$`otherNonCashItems`
      }
      if (!is.null(self$`freeCashFlow`)) {
        CashFlowStatementObject[['freeCashFlow']] <- self$`freeCashFlow`
      }

      CashFlowStatementObject
    },
    fromJSON = function(CashFlowStatementJson) {
      CashFlowStatementObject <- jsonlite::fromJSON(CashFlowStatementJson)
      if (!is.null(CashFlowStatementObject$`operatingCashFlow`)) {
        self$`operatingCashFlow` <- CashFlowStatementObject$`operatingCashFlow`
      }
      if (!is.null(CashFlowStatementObject$`paymentsForOperatingActivities`)) {
        self$`paymentsForOperatingActivities` <- CashFlowStatementObject$`paymentsForOperatingActivities`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromOperatingActivities`)) {
        self$`proceedsFromOperatingActivities` <- CashFlowStatementObject$`proceedsFromOperatingActivities`
      }
      if (!is.null(CashFlowStatementObject$`changeInOperatingLiabilities`)) {
        self$`changeInOperatingLiabilities` <- CashFlowStatementObject$`changeInOperatingLiabilities`
      }
      if (!is.null(CashFlowStatementObject$`changeInOperatingAssets`)) {
        self$`changeInOperatingAssets` <- CashFlowStatementObject$`changeInOperatingAssets`
      }
      if (!is.null(CashFlowStatementObject$`depreciationDepletionAndAmortization`)) {
        self$`depreciationDepletionAndAmortization` <- CashFlowStatementObject$`depreciationDepletionAndAmortization`
      }
      if (!is.null(CashFlowStatementObject$`capitalExpenditures`)) {
        self$`capitalExpenditures` <- CashFlowStatementObject$`capitalExpenditures`
      }
      if (!is.null(CashFlowStatementObject$`changeInReceivables`)) {
        self$`changeInReceivables` <- CashFlowStatementObject$`changeInReceivables`
      }
      if (!is.null(CashFlowStatementObject$`changeInInventory`)) {
        self$`changeInInventory` <- CashFlowStatementObject$`changeInInventory`
      }
      if (!is.null(CashFlowStatementObject$`profitLoss`)) {
        self$`profitLoss` <- CashFlowStatementObject$`profitLoss`
      }
      if (!is.null(CashFlowStatementObject$`investments`)) {
        self$`investments` <- CashFlowStatementObject$`investments`
      }
      if (!is.null(CashFlowStatementObject$`cashFlowFromInvestment`)) {
        self$`cashFlowFromInvestment` <- CashFlowStatementObject$`cashFlowFromInvestment`
      }
      if (!is.null(CashFlowStatementObject$`cashFlowFromFinancing`)) {
        self$`cashFlowFromFinancing` <- CashFlowStatementObject$`cashFlowFromFinancing`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromRepaymentsOfShortTermDebt`)) {
        self$`proceedsFromRepaymentsOfShortTermDebt` <- CashFlowStatementObject$`proceedsFromRepaymentsOfShortTermDebt`
      }
      if (!is.null(CashFlowStatementObject$`paymentsForRepurchaseOfCommonStock`)) {
        self$`paymentsForRepurchaseOfCommonStock` <- CashFlowStatementObject$`paymentsForRepurchaseOfCommonStock`
      }
      if (!is.null(CashFlowStatementObject$`paymentsForRepurchaseOfEquity`)) {
        self$`paymentsForRepurchaseOfEquity` <- CashFlowStatementObject$`paymentsForRepurchaseOfEquity`
      }
      if (!is.null(CashFlowStatementObject$`paymentsForRepurchaseOfPreferredStock`)) {
        self$`paymentsForRepurchaseOfPreferredStock` <- CashFlowStatementObject$`paymentsForRepurchaseOfPreferredStock`
      }
      if (!is.null(CashFlowStatementObject$`dividendPayout`)) {
        self$`dividendPayout` <- CashFlowStatementObject$`dividendPayout`
      }
      if (!is.null(CashFlowStatementObject$`dividendPayoutCommonStock`)) {
        self$`dividendPayoutCommonStock` <- CashFlowStatementObject$`dividendPayoutCommonStock`
      }
      if (!is.null(CashFlowStatementObject$`dividendPayoutPreferredStock`)) {
        self$`dividendPayoutPreferredStock` <- CashFlowStatementObject$`dividendPayoutPreferredStock`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromIssuanceOfCommonStock`)) {
        self$`proceedsFromIssuanceOfCommonStock` <- CashFlowStatementObject$`proceedsFromIssuanceOfCommonStock`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`)) {
        self$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet` <- CashFlowStatementObject$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromIssuanceOfPreferredStock`)) {
        self$`proceedsFromIssuanceOfPreferredStock` <- CashFlowStatementObject$`proceedsFromIssuanceOfPreferredStock`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromRepurchaseOfEquity`)) {
        self$`proceedsFromRepurchaseOfEquity` <- CashFlowStatementObject$`proceedsFromRepurchaseOfEquity`
      }
      if (!is.null(CashFlowStatementObject$`proceedsFromSaleOfTreasuryStock`)) {
        self$`proceedsFromSaleOfTreasuryStock` <- CashFlowStatementObject$`proceedsFromSaleOfTreasuryStock`
      }
      if (!is.null(CashFlowStatementObject$`changeInCashAndCashEquivalents`)) {
        self$`changeInCashAndCashEquivalents` <- CashFlowStatementObject$`changeInCashAndCashEquivalents`
      }
      if (!is.null(CashFlowStatementObject$`changeInExchangeRate`)) {
        self$`changeInExchangeRate` <- CashFlowStatementObject$`changeInExchangeRate`
      }
      if (!is.null(CashFlowStatementObject$`netIncome`)) {
        self$`netIncome` <- CashFlowStatementObject$`netIncome`
      }
      if (!is.null(CashFlowStatementObject$`netBorrowings`)) {
        self$`netBorrowings` <- CashFlowStatementObject$`netBorrowings`
      }
      if (!is.null(CashFlowStatementObject$`changeInWorkingCapital`)) {
        self$`changeInWorkingCapital` <- CashFlowStatementObject$`changeInWorkingCapital`
      }
      if (!is.null(CashFlowStatementObject$`otherNonCashItems`)) {
        self$`otherNonCashItems` <- CashFlowStatementObject$`otherNonCashItems`
      }
      if (!is.null(CashFlowStatementObject$`freeCashFlow`)) {
        self$`freeCashFlow` <- CashFlowStatementObject$`freeCashFlow`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "operatingCashFlow": %d,
           "paymentsForOperatingActivities": %d,
           "proceedsFromOperatingActivities": %d,
           "changeInOperatingLiabilities": %d,
           "changeInOperatingAssets": %d,
           "depreciationDepletionAndAmortization": %d,
           "capitalExpenditures": %d,
           "changeInReceivables": %d,
           "changeInInventory": %d,
           "profitLoss": %d,
           "investments": %d,
           "cashFlowFromInvestment": %d,
           "cashFlowFromFinancing": %d,
           "proceedsFromRepaymentsOfShortTermDebt": %d,
           "paymentsForRepurchaseOfCommonStock": %d,
           "paymentsForRepurchaseOfEquity": %d,
           "paymentsForRepurchaseOfPreferredStock": %d,
           "dividendPayout": %d,
           "dividendPayoutCommonStock": %d,
           "dividendPayoutPreferredStock": %d,
           "proceedsFromIssuanceOfCommonStock": %d,
           "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": %d,
           "proceedsFromIssuanceOfPreferredStock": %d,
           "proceedsFromRepurchaseOfEquity": %d,
           "proceedsFromSaleOfTreasuryStock": %d,
           "changeInCashAndCashEquivalents": %d,
           "changeInExchangeRate": %d,
           "netIncome": %d,
           "netBorrowings": %d,
           "changeInWorkingCapital": %d,
           "otherNonCashItems": %d,
           "freeCashFlow": %d
        }',
        self$`operatingCashFlow`,
        self$`paymentsForOperatingActivities`,
        self$`proceedsFromOperatingActivities`,
        self$`changeInOperatingLiabilities`,
        self$`changeInOperatingAssets`,
        self$`depreciationDepletionAndAmortization`,
        self$`capitalExpenditures`,
        self$`changeInReceivables`,
        self$`changeInInventory`,
        self$`profitLoss`,
        self$`investments`,
        self$`cashFlowFromInvestment`,
        self$`cashFlowFromFinancing`,
        self$`proceedsFromRepaymentsOfShortTermDebt`,
        self$`paymentsForRepurchaseOfCommonStock`,
        self$`paymentsForRepurchaseOfEquity`,
        self$`paymentsForRepurchaseOfPreferredStock`,
        self$`dividendPayout`,
        self$`dividendPayoutCommonStock`,
        self$`dividendPayoutPreferredStock`,
        self$`proceedsFromIssuanceOfCommonStock`,
        self$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`,
        self$`proceedsFromIssuanceOfPreferredStock`,
        self$`proceedsFromRepurchaseOfEquity`,
        self$`proceedsFromSaleOfTreasuryStock`,
        self$`changeInCashAndCashEquivalents`,
        self$`changeInExchangeRate`,
        self$`netIncome`,
        self$`netBorrowings`,
        self$`changeInWorkingCapital`,
        self$`otherNonCashItems`,
        self$`freeCashFlow`
      )
    },
    fromJSONString = function(CashFlowStatementJson) {
      CashFlowStatementObject <- jsonlite::fromJSON(CashFlowStatementJson)
      self$`operatingCashFlow` <- CashFlowStatementObject$`operatingCashFlow`
      self$`paymentsForOperatingActivities` <- CashFlowStatementObject$`paymentsForOperatingActivities`
      self$`proceedsFromOperatingActivities` <- CashFlowStatementObject$`proceedsFromOperatingActivities`
      self$`changeInOperatingLiabilities` <- CashFlowStatementObject$`changeInOperatingLiabilities`
      self$`changeInOperatingAssets` <- CashFlowStatementObject$`changeInOperatingAssets`
      self$`depreciationDepletionAndAmortization` <- CashFlowStatementObject$`depreciationDepletionAndAmortization`
      self$`capitalExpenditures` <- CashFlowStatementObject$`capitalExpenditures`
      self$`changeInReceivables` <- CashFlowStatementObject$`changeInReceivables`
      self$`changeInInventory` <- CashFlowStatementObject$`changeInInventory`
      self$`profitLoss` <- CashFlowStatementObject$`profitLoss`
      self$`investments` <- CashFlowStatementObject$`investments`
      self$`cashFlowFromInvestment` <- CashFlowStatementObject$`cashFlowFromInvestment`
      self$`cashFlowFromFinancing` <- CashFlowStatementObject$`cashFlowFromFinancing`
      self$`proceedsFromRepaymentsOfShortTermDebt` <- CashFlowStatementObject$`proceedsFromRepaymentsOfShortTermDebt`
      self$`paymentsForRepurchaseOfCommonStock` <- CashFlowStatementObject$`paymentsForRepurchaseOfCommonStock`
      self$`paymentsForRepurchaseOfEquity` <- CashFlowStatementObject$`paymentsForRepurchaseOfEquity`
      self$`paymentsForRepurchaseOfPreferredStock` <- CashFlowStatementObject$`paymentsForRepurchaseOfPreferredStock`
      self$`dividendPayout` <- CashFlowStatementObject$`dividendPayout`
      self$`dividendPayoutCommonStock` <- CashFlowStatementObject$`dividendPayoutCommonStock`
      self$`dividendPayoutPreferredStock` <- CashFlowStatementObject$`dividendPayoutPreferredStock`
      self$`proceedsFromIssuanceOfCommonStock` <- CashFlowStatementObject$`proceedsFromIssuanceOfCommonStock`
      self$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet` <- CashFlowStatementObject$`proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet`
      self$`proceedsFromIssuanceOfPreferredStock` <- CashFlowStatementObject$`proceedsFromIssuanceOfPreferredStock`
      self$`proceedsFromRepurchaseOfEquity` <- CashFlowStatementObject$`proceedsFromRepurchaseOfEquity`
      self$`proceedsFromSaleOfTreasuryStock` <- CashFlowStatementObject$`proceedsFromSaleOfTreasuryStock`
      self$`changeInCashAndCashEquivalents` <- CashFlowStatementObject$`changeInCashAndCashEquivalents`
      self$`changeInExchangeRate` <- CashFlowStatementObject$`changeInExchangeRate`
      self$`netIncome` <- CashFlowStatementObject$`netIncome`
      self$`netBorrowings` <- CashFlowStatementObject$`netBorrowings`
      self$`changeInWorkingCapital` <- CashFlowStatementObject$`changeInWorkingCapital`
      self$`otherNonCashItems` <- CashFlowStatementObject$`otherNonCashItems`
      self$`freeCashFlow` <- CashFlowStatementObject$`freeCashFlow`
    }
  )
)
