# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' FinancialReport Class
#'
#' @field balanceSheet 
#' @field cashFlowStatement 
#' @field incomeStatement 
#' @field startDate 
#' @field endDate 
#' @field fiscalPeriod 
#' @field year 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FinancialReport <- R6::R6Class(
  'FinancialReport',
  public = list(
    `balanceSheet` = NULL,
    `cashFlowStatement` = NULL,
    `incomeStatement` = NULL,
    `startDate` = NULL,
    `endDate` = NULL,
    `fiscalPeriod` = NULL,
    `year` = NULL,
    initialize = function(`balanceSheet`, `cashFlowStatement`, `incomeStatement`, `startDate`, `endDate`, `fiscalPeriod`, `year`){
      if (!missing(`balanceSheet`)) {
        stopifnot(R6::is.R6(`balanceSheet`))
        self$`balanceSheet` <- `balanceSheet`
      }
      if (!missing(`cashFlowStatement`)) {
        stopifnot(R6::is.R6(`cashFlowStatement`))
        self$`cashFlowStatement` <- `cashFlowStatement`
      }
      if (!missing(`incomeStatement`)) {
        stopifnot(R6::is.R6(`incomeStatement`))
        self$`incomeStatement` <- `incomeStatement`
      }
      if (!missing(`startDate`)) {
        stopifnot(is.character(`startDate`), length(`startDate`) == 1)
        self$`startDate` <- `startDate`
      }
      if (!missing(`endDate`)) {
        stopifnot(is.character(`endDate`), length(`endDate`) == 1)
        self$`endDate` <- `endDate`
      }
      if (!missing(`fiscalPeriod`)) {
        stopifnot(R6::is.R6(`fiscalPeriod`))
        self$`fiscalPeriod` <- `fiscalPeriod`
      }
      if (!missing(`year`)) {
        stopifnot(is.numeric(`year`), length(`year`) == 1)
        self$`year` <- `year`
      }
    },
    toJSON = function() {
      FinancialReportObject <- list()
      if (!is.null(self$`balanceSheet`)) {
        FinancialReportObject[['balanceSheet']] <- self$`balanceSheet`$toJSON()
      }
      if (!is.null(self$`cashFlowStatement`)) {
        FinancialReportObject[['cashFlowStatement']] <- self$`cashFlowStatement`$toJSON()
      }
      if (!is.null(self$`incomeStatement`)) {
        FinancialReportObject[['incomeStatement']] <- self$`incomeStatement`$toJSON()
      }
      if (!is.null(self$`startDate`)) {
        FinancialReportObject[['startDate']] <- self$`startDate`
      }
      if (!is.null(self$`endDate`)) {
        FinancialReportObject[['endDate']] <- self$`endDate`
      }
      if (!is.null(self$`fiscalPeriod`)) {
        FinancialReportObject[['fiscalPeriod']] <- self$`fiscalPeriod`$toJSON()
      }
      if (!is.null(self$`year`)) {
        FinancialReportObject[['year']] <- self$`year`
      }

      FinancialReportObject
    },
    fromJSON = function(FinancialReportJson) {
      FinancialReportObject <- jsonlite::fromJSON(FinancialReportJson)
      if (!is.null(FinancialReportObject$`balanceSheet`)) {
        balanceSheetObject <- BalanceSheet$new()
        balanceSheetObject$fromJSON(jsonlite::toJSON(FinancialReportObject$balanceSheet, auto_unbox = TRUE))
        self$`balanceSheet` <- balanceSheetObject
      }
      if (!is.null(FinancialReportObject$`cashFlowStatement`)) {
        cashFlowStatementObject <- CashFlowStatement$new()
        cashFlowStatementObject$fromJSON(jsonlite::toJSON(FinancialReportObject$cashFlowStatement, auto_unbox = TRUE))
        self$`cashFlowStatement` <- cashFlowStatementObject
      }
      if (!is.null(FinancialReportObject$`incomeStatement`)) {
        incomeStatementObject <- IncomeStatement$new()
        incomeStatementObject$fromJSON(jsonlite::toJSON(FinancialReportObject$incomeStatement, auto_unbox = TRUE))
        self$`incomeStatement` <- incomeStatementObject
      }
      if (!is.null(FinancialReportObject$`startDate`)) {
        self$`startDate` <- FinancialReportObject$`startDate`
      }
      if (!is.null(FinancialReportObject$`endDate`)) {
        self$`endDate` <- FinancialReportObject$`endDate`
      }
      if (!is.null(FinancialReportObject$`fiscalPeriod`)) {
        fiscalPeriodObject <- FiscalPeriod$new()
        fiscalPeriodObject$fromJSON(jsonlite::toJSON(FinancialReportObject$fiscalPeriod, auto_unbox = TRUE))
        self$`fiscalPeriod` <- fiscalPeriodObject
      }
      if (!is.null(FinancialReportObject$`year`)) {
        self$`year` <- FinancialReportObject$`year`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "balanceSheet": %s,
           "cashFlowStatement": %s,
           "incomeStatement": %s,
           "startDate": %s,
           "endDate": %s,
           "fiscalPeriod": %s,
           "year": %d
        }',
        self$`balanceSheet`$toJSON(),
        self$`cashFlowStatement`$toJSON(),
        self$`incomeStatement`$toJSON(),
        self$`startDate`,
        self$`endDate`,
        self$`fiscalPeriod`$toJSON(),
        self$`year`
      )
    },
    fromJSONString = function(FinancialReportJson) {
      FinancialReportObject <- jsonlite::fromJSON(FinancialReportJson)
      BalanceSheetObject <- BalanceSheet$new()
      self$`balanceSheet` <- BalanceSheetObject$fromJSON(jsonlite::toJSON(FinancialReportObject$balanceSheet, auto_unbox = TRUE))
      CashFlowStatementObject <- CashFlowStatement$new()
      self$`cashFlowStatement` <- CashFlowStatementObject$fromJSON(jsonlite::toJSON(FinancialReportObject$cashFlowStatement, auto_unbox = TRUE))
      IncomeStatementObject <- IncomeStatement$new()
      self$`incomeStatement` <- IncomeStatementObject$fromJSON(jsonlite::toJSON(FinancialReportObject$incomeStatement, auto_unbox = TRUE))
      self$`startDate` <- FinancialReportObject$`startDate`
      self$`endDate` <- FinancialReportObject$`endDate`
      FiscalPeriodObject <- FiscalPeriod$new()
      self$`fiscalPeriod` <- FiscalPeriodObject$fromJSON(jsonlite::toJSON(FinancialReportObject$fiscalPeriod, auto_unbox = TRUE))
      self$`year` <- FinancialReportObject$`year`
    }
  )
)
