# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Image Class
#'
#' @field size 
#' @field extension 
#' @field filename 
#' @field contentType 
#' @field webPath 
#' @field webPathname 
#' @field width 
#' @field height 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Image <- R6::R6Class(
  'Image',
  public = list(
    `size` = NULL,
    `extension` = NULL,
    `filename` = NULL,
    `contentType` = NULL,
    `webPath` = NULL,
    `webPathname` = NULL,
    `width` = NULL,
    `height` = NULL,
    initialize = function(`size`, `extension`, `filename`, `contentType`, `webPath`, `webPathname`, `width`, `height`){
      if (!missing(`size`)) {
        stopifnot(is.numeric(`size`), length(`size`) == 1)
        self$`size` <- `size`
      }
      if (!missing(`extension`)) {
        stopifnot(is.character(`extension`), length(`extension`) == 1)
        self$`extension` <- `extension`
      }
      if (!missing(`filename`)) {
        stopifnot(is.character(`filename`), length(`filename`) == 1)
        self$`filename` <- `filename`
      }
      if (!missing(`contentType`)) {
        stopifnot(is.character(`contentType`), length(`contentType`) == 1)
        self$`contentType` <- `contentType`
      }
      if (!missing(`webPath`)) {
        stopifnot(is.character(`webPath`), length(`webPath`) == 1)
        self$`webPath` <- `webPath`
      }
      if (!missing(`webPathname`)) {
        stopifnot(is.character(`webPathname`), length(`webPathname`) == 1)
        self$`webPathname` <- `webPathname`
      }
      if (!missing(`width`)) {
        stopifnot(is.numeric(`width`), length(`width`) == 1)
        self$`width` <- `width`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
    },
    toJSON = function() {
      ImageObject <- list()
      if (!is.null(self$`size`)) {
        ImageObject[['size']] <- self$`size`
      }
      if (!is.null(self$`extension`)) {
        ImageObject[['extension']] <- self$`extension`
      }
      if (!is.null(self$`filename`)) {
        ImageObject[['filename']] <- self$`filename`
      }
      if (!is.null(self$`contentType`)) {
        ImageObject[['contentType']] <- self$`contentType`
      }
      if (!is.null(self$`webPath`)) {
        ImageObject[['webPath']] <- self$`webPath`
      }
      if (!is.null(self$`webPathname`)) {
        ImageObject[['webPathname']] <- self$`webPathname`
      }
      if (!is.null(self$`width`)) {
        ImageObject[['width']] <- self$`width`
      }
      if (!is.null(self$`height`)) {
        ImageObject[['height']] <- self$`height`
      }

      ImageObject
    },
    fromJSON = function(ImageJson) {
      ImageObject <- jsonlite::fromJSON(ImageJson)
      if (!is.null(ImageObject$`size`)) {
        self$`size` <- ImageObject$`size`
      }
      if (!is.null(ImageObject$`extension`)) {
        self$`extension` <- ImageObject$`extension`
      }
      if (!is.null(ImageObject$`filename`)) {
        self$`filename` <- ImageObject$`filename`
      }
      if (!is.null(ImageObject$`contentType`)) {
        self$`contentType` <- ImageObject$`contentType`
      }
      if (!is.null(ImageObject$`webPath`)) {
        self$`webPath` <- ImageObject$`webPath`
      }
      if (!is.null(ImageObject$`webPathname`)) {
        self$`webPathname` <- ImageObject$`webPathname`
      }
      if (!is.null(ImageObject$`width`)) {
        self$`width` <- ImageObject$`width`
      }
      if (!is.null(ImageObject$`height`)) {
        self$`height` <- ImageObject$`height`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "size": %d,
           "extension": %s,
           "filename": %s,
           "contentType": %s,
           "webPath": %s,
           "webPathname": %s,
           "width": %d,
           "height": %d
        }',
        self$`size`,
        self$`extension`,
        self$`filename`,
        self$`contentType`,
        self$`webPath`,
        self$`webPathname`,
        self$`width`,
        self$`height`
      )
    },
    fromJSONString = function(ImageJson) {
      ImageObject <- jsonlite::fromJSON(ImageJson)
      self$`size` <- ImageObject$`size`
      self$`extension` <- ImageObject$`extension`
      self$`filename` <- ImageObject$`filename`
      self$`contentType` <- ImageObject$`contentType`
      self$`webPath` <- ImageObject$`webPath`
      self$`webPathname` <- ImageObject$`webPathname`
      self$`width` <- ImageObject$`width`
      self$`height` <- ImageObject$`height`
    }
  )
)
