# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' IncomeStatement Class
#'
#' @field grossProfit 
#' @field revenue 
#' @field costOfRevenue 
#' @field costOfGoodsAndServicesSold 
#' @field operatingIncome 
#' @field sellingGeneralAndAdministrative 
#' @field researchAndDevelopment 
#' @field operatingExpenses 
#' @field investmentIncomeNet 
#' @field netInterestIncome 
#' @field interestIncome 
#' @field interestExpense 
#' @field nonInterestIncome 
#' @field otherNonOperatingIncome 
#' @field depreciation 
#' @field depreciationAndAmortization 
#' @field incomeBeforeTax 
#' @field incomeTaxExpense 
#' @field interestAndDebtExpense 
#' @field netIncomeFromContinuingOperations 
#' @field comprehensiveIncomeNetOfTax 
#' @field ebit 
#' @field ebitda 
#' @field netIncome 
#' @field effectOfAccountingCharges 
#' @field taxProvision 
#' @field sellingAndMarketingExpenses 
#' @field extraordinaryItems 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IncomeStatement <- R6::R6Class(
  'IncomeStatement',
  public = list(
    `grossProfit` = NULL,
    `revenue` = NULL,
    `costOfRevenue` = NULL,
    `costOfGoodsAndServicesSold` = NULL,
    `operatingIncome` = NULL,
    `sellingGeneralAndAdministrative` = NULL,
    `researchAndDevelopment` = NULL,
    `operatingExpenses` = NULL,
    `investmentIncomeNet` = NULL,
    `netInterestIncome` = NULL,
    `interestIncome` = NULL,
    `interestExpense` = NULL,
    `nonInterestIncome` = NULL,
    `otherNonOperatingIncome` = NULL,
    `depreciation` = NULL,
    `depreciationAndAmortization` = NULL,
    `incomeBeforeTax` = NULL,
    `incomeTaxExpense` = NULL,
    `interestAndDebtExpense` = NULL,
    `netIncomeFromContinuingOperations` = NULL,
    `comprehensiveIncomeNetOfTax` = NULL,
    `ebit` = NULL,
    `ebitda` = NULL,
    `netIncome` = NULL,
    `effectOfAccountingCharges` = NULL,
    `taxProvision` = NULL,
    `sellingAndMarketingExpenses` = NULL,
    `extraordinaryItems` = NULL,
    initialize = function(`grossProfit`, `revenue`, `costOfRevenue`, `costOfGoodsAndServicesSold`, `operatingIncome`, `sellingGeneralAndAdministrative`, `researchAndDevelopment`, `operatingExpenses`, `investmentIncomeNet`, `netInterestIncome`, `interestIncome`, `interestExpense`, `nonInterestIncome`, `otherNonOperatingIncome`, `depreciation`, `depreciationAndAmortization`, `incomeBeforeTax`, `incomeTaxExpense`, `interestAndDebtExpense`, `netIncomeFromContinuingOperations`, `comprehensiveIncomeNetOfTax`, `ebit`, `ebitda`, `netIncome`, `effectOfAccountingCharges`, `taxProvision`, `sellingAndMarketingExpenses`, `extraordinaryItems`){
      if (!missing(`grossProfit`)) {
        stopifnot(is.numeric(`grossProfit`), length(`grossProfit`) == 1)
        self$`grossProfit` <- `grossProfit`
      }
      if (!missing(`revenue`)) {
        stopifnot(is.numeric(`revenue`), length(`revenue`) == 1)
        self$`revenue` <- `revenue`
      }
      if (!missing(`costOfRevenue`)) {
        stopifnot(is.numeric(`costOfRevenue`), length(`costOfRevenue`) == 1)
        self$`costOfRevenue` <- `costOfRevenue`
      }
      if (!missing(`costOfGoodsAndServicesSold`)) {
        stopifnot(is.numeric(`costOfGoodsAndServicesSold`), length(`costOfGoodsAndServicesSold`) == 1)
        self$`costOfGoodsAndServicesSold` <- `costOfGoodsAndServicesSold`
      }
      if (!missing(`operatingIncome`)) {
        stopifnot(is.numeric(`operatingIncome`), length(`operatingIncome`) == 1)
        self$`operatingIncome` <- `operatingIncome`
      }
      if (!missing(`sellingGeneralAndAdministrative`)) {
        stopifnot(is.numeric(`sellingGeneralAndAdministrative`), length(`sellingGeneralAndAdministrative`) == 1)
        self$`sellingGeneralAndAdministrative` <- `sellingGeneralAndAdministrative`
      }
      if (!missing(`researchAndDevelopment`)) {
        stopifnot(is.numeric(`researchAndDevelopment`), length(`researchAndDevelopment`) == 1)
        self$`researchAndDevelopment` <- `researchAndDevelopment`
      }
      if (!missing(`operatingExpenses`)) {
        stopifnot(is.numeric(`operatingExpenses`), length(`operatingExpenses`) == 1)
        self$`operatingExpenses` <- `operatingExpenses`
      }
      if (!missing(`investmentIncomeNet`)) {
        stopifnot(is.numeric(`investmentIncomeNet`), length(`investmentIncomeNet`) == 1)
        self$`investmentIncomeNet` <- `investmentIncomeNet`
      }
      if (!missing(`netInterestIncome`)) {
        stopifnot(is.numeric(`netInterestIncome`), length(`netInterestIncome`) == 1)
        self$`netInterestIncome` <- `netInterestIncome`
      }
      if (!missing(`interestIncome`)) {
        stopifnot(is.numeric(`interestIncome`), length(`interestIncome`) == 1)
        self$`interestIncome` <- `interestIncome`
      }
      if (!missing(`interestExpense`)) {
        stopifnot(is.numeric(`interestExpense`), length(`interestExpense`) == 1)
        self$`interestExpense` <- `interestExpense`
      }
      if (!missing(`nonInterestIncome`)) {
        stopifnot(is.numeric(`nonInterestIncome`), length(`nonInterestIncome`) == 1)
        self$`nonInterestIncome` <- `nonInterestIncome`
      }
      if (!missing(`otherNonOperatingIncome`)) {
        stopifnot(is.numeric(`otherNonOperatingIncome`), length(`otherNonOperatingIncome`) == 1)
        self$`otherNonOperatingIncome` <- `otherNonOperatingIncome`
      }
      if (!missing(`depreciation`)) {
        stopifnot(is.numeric(`depreciation`), length(`depreciation`) == 1)
        self$`depreciation` <- `depreciation`
      }
      if (!missing(`depreciationAndAmortization`)) {
        stopifnot(is.numeric(`depreciationAndAmortization`), length(`depreciationAndAmortization`) == 1)
        self$`depreciationAndAmortization` <- `depreciationAndAmortization`
      }
      if (!missing(`incomeBeforeTax`)) {
        stopifnot(is.numeric(`incomeBeforeTax`), length(`incomeBeforeTax`) == 1)
        self$`incomeBeforeTax` <- `incomeBeforeTax`
      }
      if (!missing(`incomeTaxExpense`)) {
        stopifnot(is.numeric(`incomeTaxExpense`), length(`incomeTaxExpense`) == 1)
        self$`incomeTaxExpense` <- `incomeTaxExpense`
      }
      if (!missing(`interestAndDebtExpense`)) {
        stopifnot(is.numeric(`interestAndDebtExpense`), length(`interestAndDebtExpense`) == 1)
        self$`interestAndDebtExpense` <- `interestAndDebtExpense`
      }
      if (!missing(`netIncomeFromContinuingOperations`)) {
        stopifnot(is.numeric(`netIncomeFromContinuingOperations`), length(`netIncomeFromContinuingOperations`) == 1)
        self$`netIncomeFromContinuingOperations` <- `netIncomeFromContinuingOperations`
      }
      if (!missing(`comprehensiveIncomeNetOfTax`)) {
        stopifnot(is.numeric(`comprehensiveIncomeNetOfTax`), length(`comprehensiveIncomeNetOfTax`) == 1)
        self$`comprehensiveIncomeNetOfTax` <- `comprehensiveIncomeNetOfTax`
      }
      if (!missing(`ebit`)) {
        stopifnot(is.numeric(`ebit`), length(`ebit`) == 1)
        self$`ebit` <- `ebit`
      }
      if (!missing(`ebitda`)) {
        stopifnot(is.numeric(`ebitda`), length(`ebitda`) == 1)
        self$`ebitda` <- `ebitda`
      }
      if (!missing(`netIncome`)) {
        stopifnot(is.numeric(`netIncome`), length(`netIncome`) == 1)
        self$`netIncome` <- `netIncome`
      }
      if (!missing(`effectOfAccountingCharges`)) {
        stopifnot(is.numeric(`effectOfAccountingCharges`), length(`effectOfAccountingCharges`) == 1)
        self$`effectOfAccountingCharges` <- `effectOfAccountingCharges`
      }
      if (!missing(`taxProvision`)) {
        stopifnot(is.numeric(`taxProvision`), length(`taxProvision`) == 1)
        self$`taxProvision` <- `taxProvision`
      }
      if (!missing(`sellingAndMarketingExpenses`)) {
        stopifnot(is.numeric(`sellingAndMarketingExpenses`), length(`sellingAndMarketingExpenses`) == 1)
        self$`sellingAndMarketingExpenses` <- `sellingAndMarketingExpenses`
      }
      if (!missing(`extraordinaryItems`)) {
        stopifnot(is.numeric(`extraordinaryItems`), length(`extraordinaryItems`) == 1)
        self$`extraordinaryItems` <- `extraordinaryItems`
      }
    },
    toJSON = function() {
      IncomeStatementObject <- list()
      if (!is.null(self$`grossProfit`)) {
        IncomeStatementObject[['grossProfit']] <- self$`grossProfit`
      }
      if (!is.null(self$`revenue`)) {
        IncomeStatementObject[['revenue']] <- self$`revenue`
      }
      if (!is.null(self$`costOfRevenue`)) {
        IncomeStatementObject[['costOfRevenue']] <- self$`costOfRevenue`
      }
      if (!is.null(self$`costOfGoodsAndServicesSold`)) {
        IncomeStatementObject[['costOfGoodsAndServicesSold']] <- self$`costOfGoodsAndServicesSold`
      }
      if (!is.null(self$`operatingIncome`)) {
        IncomeStatementObject[['operatingIncome']] <- self$`operatingIncome`
      }
      if (!is.null(self$`sellingGeneralAndAdministrative`)) {
        IncomeStatementObject[['sellingGeneralAndAdministrative']] <- self$`sellingGeneralAndAdministrative`
      }
      if (!is.null(self$`researchAndDevelopment`)) {
        IncomeStatementObject[['researchAndDevelopment']] <- self$`researchAndDevelopment`
      }
      if (!is.null(self$`operatingExpenses`)) {
        IncomeStatementObject[['operatingExpenses']] <- self$`operatingExpenses`
      }
      if (!is.null(self$`investmentIncomeNet`)) {
        IncomeStatementObject[['investmentIncomeNet']] <- self$`investmentIncomeNet`
      }
      if (!is.null(self$`netInterestIncome`)) {
        IncomeStatementObject[['netInterestIncome']] <- self$`netInterestIncome`
      }
      if (!is.null(self$`interestIncome`)) {
        IncomeStatementObject[['interestIncome']] <- self$`interestIncome`
      }
      if (!is.null(self$`interestExpense`)) {
        IncomeStatementObject[['interestExpense']] <- self$`interestExpense`
      }
      if (!is.null(self$`nonInterestIncome`)) {
        IncomeStatementObject[['nonInterestIncome']] <- self$`nonInterestIncome`
      }
      if (!is.null(self$`otherNonOperatingIncome`)) {
        IncomeStatementObject[['otherNonOperatingIncome']] <- self$`otherNonOperatingIncome`
      }
      if (!is.null(self$`depreciation`)) {
        IncomeStatementObject[['depreciation']] <- self$`depreciation`
      }
      if (!is.null(self$`depreciationAndAmortization`)) {
        IncomeStatementObject[['depreciationAndAmortization']] <- self$`depreciationAndAmortization`
      }
      if (!is.null(self$`incomeBeforeTax`)) {
        IncomeStatementObject[['incomeBeforeTax']] <- self$`incomeBeforeTax`
      }
      if (!is.null(self$`incomeTaxExpense`)) {
        IncomeStatementObject[['incomeTaxExpense']] <- self$`incomeTaxExpense`
      }
      if (!is.null(self$`interestAndDebtExpense`)) {
        IncomeStatementObject[['interestAndDebtExpense']] <- self$`interestAndDebtExpense`
      }
      if (!is.null(self$`netIncomeFromContinuingOperations`)) {
        IncomeStatementObject[['netIncomeFromContinuingOperations']] <- self$`netIncomeFromContinuingOperations`
      }
      if (!is.null(self$`comprehensiveIncomeNetOfTax`)) {
        IncomeStatementObject[['comprehensiveIncomeNetOfTax']] <- self$`comprehensiveIncomeNetOfTax`
      }
      if (!is.null(self$`ebit`)) {
        IncomeStatementObject[['ebit']] <- self$`ebit`
      }
      if (!is.null(self$`ebitda`)) {
        IncomeStatementObject[['ebitda']] <- self$`ebitda`
      }
      if (!is.null(self$`netIncome`)) {
        IncomeStatementObject[['netIncome']] <- self$`netIncome`
      }
      if (!is.null(self$`effectOfAccountingCharges`)) {
        IncomeStatementObject[['effectOfAccountingCharges']] <- self$`effectOfAccountingCharges`
      }
      if (!is.null(self$`taxProvision`)) {
        IncomeStatementObject[['taxProvision']] <- self$`taxProvision`
      }
      if (!is.null(self$`sellingAndMarketingExpenses`)) {
        IncomeStatementObject[['sellingAndMarketingExpenses']] <- self$`sellingAndMarketingExpenses`
      }
      if (!is.null(self$`extraordinaryItems`)) {
        IncomeStatementObject[['extraordinaryItems']] <- self$`extraordinaryItems`
      }

      IncomeStatementObject
    },
    fromJSON = function(IncomeStatementJson) {
      IncomeStatementObject <- jsonlite::fromJSON(IncomeStatementJson)
      if (!is.null(IncomeStatementObject$`grossProfit`)) {
        self$`grossProfit` <- IncomeStatementObject$`grossProfit`
      }
      if (!is.null(IncomeStatementObject$`revenue`)) {
        self$`revenue` <- IncomeStatementObject$`revenue`
      }
      if (!is.null(IncomeStatementObject$`costOfRevenue`)) {
        self$`costOfRevenue` <- IncomeStatementObject$`costOfRevenue`
      }
      if (!is.null(IncomeStatementObject$`costOfGoodsAndServicesSold`)) {
        self$`costOfGoodsAndServicesSold` <- IncomeStatementObject$`costOfGoodsAndServicesSold`
      }
      if (!is.null(IncomeStatementObject$`operatingIncome`)) {
        self$`operatingIncome` <- IncomeStatementObject$`operatingIncome`
      }
      if (!is.null(IncomeStatementObject$`sellingGeneralAndAdministrative`)) {
        self$`sellingGeneralAndAdministrative` <- IncomeStatementObject$`sellingGeneralAndAdministrative`
      }
      if (!is.null(IncomeStatementObject$`researchAndDevelopment`)) {
        self$`researchAndDevelopment` <- IncomeStatementObject$`researchAndDevelopment`
      }
      if (!is.null(IncomeStatementObject$`operatingExpenses`)) {
        self$`operatingExpenses` <- IncomeStatementObject$`operatingExpenses`
      }
      if (!is.null(IncomeStatementObject$`investmentIncomeNet`)) {
        self$`investmentIncomeNet` <- IncomeStatementObject$`investmentIncomeNet`
      }
      if (!is.null(IncomeStatementObject$`netInterestIncome`)) {
        self$`netInterestIncome` <- IncomeStatementObject$`netInterestIncome`
      }
      if (!is.null(IncomeStatementObject$`interestIncome`)) {
        self$`interestIncome` <- IncomeStatementObject$`interestIncome`
      }
      if (!is.null(IncomeStatementObject$`interestExpense`)) {
        self$`interestExpense` <- IncomeStatementObject$`interestExpense`
      }
      if (!is.null(IncomeStatementObject$`nonInterestIncome`)) {
        self$`nonInterestIncome` <- IncomeStatementObject$`nonInterestIncome`
      }
      if (!is.null(IncomeStatementObject$`otherNonOperatingIncome`)) {
        self$`otherNonOperatingIncome` <- IncomeStatementObject$`otherNonOperatingIncome`
      }
      if (!is.null(IncomeStatementObject$`depreciation`)) {
        self$`depreciation` <- IncomeStatementObject$`depreciation`
      }
      if (!is.null(IncomeStatementObject$`depreciationAndAmortization`)) {
        self$`depreciationAndAmortization` <- IncomeStatementObject$`depreciationAndAmortization`
      }
      if (!is.null(IncomeStatementObject$`incomeBeforeTax`)) {
        self$`incomeBeforeTax` <- IncomeStatementObject$`incomeBeforeTax`
      }
      if (!is.null(IncomeStatementObject$`incomeTaxExpense`)) {
        self$`incomeTaxExpense` <- IncomeStatementObject$`incomeTaxExpense`
      }
      if (!is.null(IncomeStatementObject$`interestAndDebtExpense`)) {
        self$`interestAndDebtExpense` <- IncomeStatementObject$`interestAndDebtExpense`
      }
      if (!is.null(IncomeStatementObject$`netIncomeFromContinuingOperations`)) {
        self$`netIncomeFromContinuingOperations` <- IncomeStatementObject$`netIncomeFromContinuingOperations`
      }
      if (!is.null(IncomeStatementObject$`comprehensiveIncomeNetOfTax`)) {
        self$`comprehensiveIncomeNetOfTax` <- IncomeStatementObject$`comprehensiveIncomeNetOfTax`
      }
      if (!is.null(IncomeStatementObject$`ebit`)) {
        self$`ebit` <- IncomeStatementObject$`ebit`
      }
      if (!is.null(IncomeStatementObject$`ebitda`)) {
        self$`ebitda` <- IncomeStatementObject$`ebitda`
      }
      if (!is.null(IncomeStatementObject$`netIncome`)) {
        self$`netIncome` <- IncomeStatementObject$`netIncome`
      }
      if (!is.null(IncomeStatementObject$`effectOfAccountingCharges`)) {
        self$`effectOfAccountingCharges` <- IncomeStatementObject$`effectOfAccountingCharges`
      }
      if (!is.null(IncomeStatementObject$`taxProvision`)) {
        self$`taxProvision` <- IncomeStatementObject$`taxProvision`
      }
      if (!is.null(IncomeStatementObject$`sellingAndMarketingExpenses`)) {
        self$`sellingAndMarketingExpenses` <- IncomeStatementObject$`sellingAndMarketingExpenses`
      }
      if (!is.null(IncomeStatementObject$`extraordinaryItems`)) {
        self$`extraordinaryItems` <- IncomeStatementObject$`extraordinaryItems`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "grossProfit": %d,
           "revenue": %d,
           "costOfRevenue": %d,
           "costOfGoodsAndServicesSold": %d,
           "operatingIncome": %d,
           "sellingGeneralAndAdministrative": %d,
           "researchAndDevelopment": %d,
           "operatingExpenses": %d,
           "investmentIncomeNet": %d,
           "netInterestIncome": %d,
           "interestIncome": %d,
           "interestExpense": %d,
           "nonInterestIncome": %d,
           "otherNonOperatingIncome": %d,
           "depreciation": %d,
           "depreciationAndAmortization": %d,
           "incomeBeforeTax": %d,
           "incomeTaxExpense": %d,
           "interestAndDebtExpense": %d,
           "netIncomeFromContinuingOperations": %d,
           "comprehensiveIncomeNetOfTax": %d,
           "ebit": %d,
           "ebitda": %d,
           "netIncome": %d,
           "effectOfAccountingCharges": %d,
           "taxProvision": %d,
           "sellingAndMarketingExpenses": %d,
           "extraordinaryItems": %d
        }',
        self$`grossProfit`,
        self$`revenue`,
        self$`costOfRevenue`,
        self$`costOfGoodsAndServicesSold`,
        self$`operatingIncome`,
        self$`sellingGeneralAndAdministrative`,
        self$`researchAndDevelopment`,
        self$`operatingExpenses`,
        self$`investmentIncomeNet`,
        self$`netInterestIncome`,
        self$`interestIncome`,
        self$`interestExpense`,
        self$`nonInterestIncome`,
        self$`otherNonOperatingIncome`,
        self$`depreciation`,
        self$`depreciationAndAmortization`,
        self$`incomeBeforeTax`,
        self$`incomeTaxExpense`,
        self$`interestAndDebtExpense`,
        self$`netIncomeFromContinuingOperations`,
        self$`comprehensiveIncomeNetOfTax`,
        self$`ebit`,
        self$`ebitda`,
        self$`netIncome`,
        self$`effectOfAccountingCharges`,
        self$`taxProvision`,
        self$`sellingAndMarketingExpenses`,
        self$`extraordinaryItems`
      )
    },
    fromJSONString = function(IncomeStatementJson) {
      IncomeStatementObject <- jsonlite::fromJSON(IncomeStatementJson)
      self$`grossProfit` <- IncomeStatementObject$`grossProfit`
      self$`revenue` <- IncomeStatementObject$`revenue`
      self$`costOfRevenue` <- IncomeStatementObject$`costOfRevenue`
      self$`costOfGoodsAndServicesSold` <- IncomeStatementObject$`costOfGoodsAndServicesSold`
      self$`operatingIncome` <- IncomeStatementObject$`operatingIncome`
      self$`sellingGeneralAndAdministrative` <- IncomeStatementObject$`sellingGeneralAndAdministrative`
      self$`researchAndDevelopment` <- IncomeStatementObject$`researchAndDevelopment`
      self$`operatingExpenses` <- IncomeStatementObject$`operatingExpenses`
      self$`investmentIncomeNet` <- IncomeStatementObject$`investmentIncomeNet`
      self$`netInterestIncome` <- IncomeStatementObject$`netInterestIncome`
      self$`interestIncome` <- IncomeStatementObject$`interestIncome`
      self$`interestExpense` <- IncomeStatementObject$`interestExpense`
      self$`nonInterestIncome` <- IncomeStatementObject$`nonInterestIncome`
      self$`otherNonOperatingIncome` <- IncomeStatementObject$`otherNonOperatingIncome`
      self$`depreciation` <- IncomeStatementObject$`depreciation`
      self$`depreciationAndAmortization` <- IncomeStatementObject$`depreciationAndAmortization`
      self$`incomeBeforeTax` <- IncomeStatementObject$`incomeBeforeTax`
      self$`incomeTaxExpense` <- IncomeStatementObject$`incomeTaxExpense`
      self$`interestAndDebtExpense` <- IncomeStatementObject$`interestAndDebtExpense`
      self$`netIncomeFromContinuingOperations` <- IncomeStatementObject$`netIncomeFromContinuingOperations`
      self$`comprehensiveIncomeNetOfTax` <- IncomeStatementObject$`comprehensiveIncomeNetOfTax`
      self$`ebit` <- IncomeStatementObject$`ebit`
      self$`ebitda` <- IncomeStatementObject$`ebitda`
      self$`netIncome` <- IncomeStatementObject$`netIncome`
      self$`effectOfAccountingCharges` <- IncomeStatementObject$`effectOfAccountingCharges`
      self$`taxProvision` <- IncomeStatementObject$`taxProvision`
      self$`sellingAndMarketingExpenses` <- IncomeStatementObject$`sellingAndMarketingExpenses`
      self$`extraordinaryItems` <- IncomeStatementObject$`extraordinaryItems`
    }
  )
)
