# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Officer Class
#'
#' @field name 
#' @field role 
#' @field yearBorn 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Officer <- R6::R6Class(
  'Officer',
  public = list(
    `name` = NULL,
    `role` = NULL,
    `yearBorn` = NULL,
    initialize = function(`name`, `role`, `yearBorn`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`role`)) {
        stopifnot(is.character(`role`), length(`role`) == 1)
        self$`role` <- `role`
      }
      if (!missing(`yearBorn`)) {
        stopifnot(is.numeric(`yearBorn`), length(`yearBorn`) == 1)
        self$`yearBorn` <- `yearBorn`
      }
    },
    toJSON = function() {
      OfficerObject <- list()
      if (!is.null(self$`name`)) {
        OfficerObject[['name']] <- self$`name`
      }
      if (!is.null(self$`role`)) {
        OfficerObject[['role']] <- self$`role`
      }
      if (!is.null(self$`yearBorn`)) {
        OfficerObject[['yearBorn']] <- self$`yearBorn`
      }

      OfficerObject
    },
    fromJSON = function(OfficerJson) {
      OfficerObject <- jsonlite::fromJSON(OfficerJson)
      if (!is.null(OfficerObject$`name`)) {
        self$`name` <- OfficerObject$`name`
      }
      if (!is.null(OfficerObject$`role`)) {
        self$`role` <- OfficerObject$`role`
      }
      if (!is.null(OfficerObject$`yearBorn`)) {
        self$`yearBorn` <- OfficerObject$`yearBorn`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "role": %s,
           "yearBorn": %d
        }',
        self$`name`,
        self$`role`,
        self$`yearBorn`
      )
    },
    fromJSONString = function(OfficerJson) {
      OfficerObject <- jsonlite::fromJSON(OfficerJson)
      self$`name` <- OfficerObject$`name`
      self$`role` <- OfficerObject$`role`
      self$`yearBorn` <- OfficerObject$`yearBorn`
    }
  )
)
