# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Price Class
#'
#' @field close 
#' @field high 
#' @field low 
#' @field open 
#' @field volume 
#' @field time 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Price <- R6::R6Class(
  'Price',
  public = list(
    `close` = NULL,
    `high` = NULL,
    `low` = NULL,
    `open` = NULL,
    `volume` = NULL,
    `time` = NULL,
    initialize = function(`close`, `high`, `low`, `open`, `volume`, `time`){
      if (!missing(`close`)) {
        stopifnot(is.numeric(`close`), length(`close`) == 1)
        self$`close` <- `close`
      }
      if (!missing(`high`)) {
        stopifnot(is.numeric(`high`), length(`high`) == 1)
        self$`high` <- `high`
      }
      if (!missing(`low`)) {
        stopifnot(is.numeric(`low`), length(`low`) == 1)
        self$`low` <- `low`
      }
      if (!missing(`open`)) {
        stopifnot(is.numeric(`open`), length(`open`) == 1)
        self$`open` <- `open`
      }
      if (!missing(`volume`)) {
        stopifnot(is.numeric(`volume`), length(`volume`) == 1)
        self$`volume` <- `volume`
      }
      if (!missing(`time`)) {
        stopifnot(is.character(`time`), length(`time`) == 1)
        self$`time` <- `time`
      }
    },
    toJSON = function() {
      PriceObject <- list()
      if (!is.null(self$`close`)) {
        PriceObject[['close']] <- self$`close`
      }
      if (!is.null(self$`high`)) {
        PriceObject[['high']] <- self$`high`
      }
      if (!is.null(self$`low`)) {
        PriceObject[['low']] <- self$`low`
      }
      if (!is.null(self$`open`)) {
        PriceObject[['open']] <- self$`open`
      }
      if (!is.null(self$`volume`)) {
        PriceObject[['volume']] <- self$`volume`
      }
      if (!is.null(self$`time`)) {
        PriceObject[['time']] <- self$`time`
      }

      PriceObject
    },
    fromJSON = function(PriceJson) {
      PriceObject <- jsonlite::fromJSON(PriceJson)
      if (!is.null(PriceObject$`close`)) {
        self$`close` <- PriceObject$`close`
      }
      if (!is.null(PriceObject$`high`)) {
        self$`high` <- PriceObject$`high`
      }
      if (!is.null(PriceObject$`low`)) {
        self$`low` <- PriceObject$`low`
      }
      if (!is.null(PriceObject$`open`)) {
        self$`open` <- PriceObject$`open`
      }
      if (!is.null(PriceObject$`volume`)) {
        self$`volume` <- PriceObject$`volume`
      }
      if (!is.null(PriceObject$`time`)) {
        self$`time` <- PriceObject$`time`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "close": %d,
           "high": %d,
           "low": %d,
           "open": %d,
           "volume": %d,
           "time": %s
        }',
        self$`close`,
        self$`high`,
        self$`low`,
        self$`open`,
        self$`volume`,
        self$`time`
      )
    },
    fromJSONString = function(PriceJson) {
      PriceObject <- jsonlite::fromJSON(PriceJson)
      self$`close` <- PriceObject$`close`
      self$`high` <- PriceObject$`high`
      self$`low` <- PriceObject$`low`
      self$`open` <- PriceObject$`open`
      self$`volume` <- PriceObject$`volume`
      self$`time` <- PriceObject$`time`
    }
  )
)
