# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Publisher Class
#'
#' @field name 
#' @field homepageUrl 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Publisher <- R6::R6Class(
  'Publisher',
  public = list(
    `name` = NULL,
    `homepageUrl` = NULL,
    initialize = function(`name`, `homepageUrl`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`homepageUrl`)) {
        stopifnot(is.character(`homepageUrl`), length(`homepageUrl`) == 1)
        self$`homepageUrl` <- `homepageUrl`
      }
    },
    toJSON = function() {
      PublisherObject <- list()
      if (!is.null(self$`name`)) {
        PublisherObject[['name']] <- self$`name`
      }
      if (!is.null(self$`homepageUrl`)) {
        PublisherObject[['homepageUrl']] <- self$`homepageUrl`
      }

      PublisherObject
    },
    fromJSON = function(PublisherJson) {
      PublisherObject <- jsonlite::fromJSON(PublisherJson)
      if (!is.null(PublisherObject$`name`)) {
        self$`name` <- PublisherObject$`name`
      }
      if (!is.null(PublisherObject$`homepageUrl`)) {
        self$`homepageUrl` <- PublisherObject$`homepageUrl`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "homepageUrl": %s
        }',
        self$`name`,
        self$`homepageUrl`
      )
    },
    fromJSONString = function(PublisherJson) {
      PublisherObject <- jsonlite::fromJSON(PublisherJson)
      self$`name` <- PublisherObject$`name`
      self$`homepageUrl` <- PublisherObject$`homepageUrl`
    }
  )
)
