# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Sector Class
#'
#' @field name 
#' @field industries 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Sector <- R6::R6Class(
  'Sector',
  public = list(
    `name` = NULL,
    `industries` = NULL,
    initialize = function(`name`, `industries`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`industries`)) {
        stopifnot(is.list(`industries`), length(`industries`) != 0)
        lapply(`industries`, function(x) stopifnot(R6::is.R6(x)))
        self$`industries` <- `industries`
      }
    },
    toJSON = function() {
      SectorObject <- list()
      if (!is.null(self$`name`)) {
        SectorObject[['name']] <- self$`name`
      }
      if (!is.null(self$`industries`)) {
        SectorObject[['industries']] <- lapply(self$`industries`, function(x) x$toJSON())
      }

      SectorObject
    },
    fromJSON = function(SectorJson) {
      SectorObject <- jsonlite::fromJSON(SectorJson)
      if (!is.null(SectorObject$`name`)) {
        self$`name` <- SectorObject$`name`
      }
      if (!is.null(SectorObject$`industries`)) {
        self$`industries` <- lapply(SectorObject$`industries`, function(x) {
          industriesObject <- Industry$new()
          industriesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          industriesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "industries": [%s]
        }',
        self$`name`,
        lapply(self$`industries`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(SectorJson) {
      SectorObject <- jsonlite::fromJSON(SectorJson)
      self$`name` <- SectorObject$`name`
      self$`industries` <- lapply(SectorObject$`industries`, function(x) Industry$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
