# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' StockSplit Class
#'
#' @field executionDate 
#' @field forFactor 
#' @field toFactor 
#' @field ratio 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StockSplit <- R6::R6Class(
  'StockSplit',
  public = list(
    `executionDate` = NULL,
    `forFactor` = NULL,
    `toFactor` = NULL,
    `ratio` = NULL,
    initialize = function(`executionDate`, `forFactor`, `toFactor`, `ratio`){
      if (!missing(`executionDate`)) {
        stopifnot(is.character(`executionDate`), length(`executionDate`) == 1)
        self$`executionDate` <- `executionDate`
      }
      if (!missing(`forFactor`)) {
        stopifnot(is.numeric(`forFactor`), length(`forFactor`) == 1)
        self$`forFactor` <- `forFactor`
      }
      if (!missing(`toFactor`)) {
        stopifnot(is.numeric(`toFactor`), length(`toFactor`) == 1)
        self$`toFactor` <- `toFactor`
      }
      if (!missing(`ratio`)) {
        stopifnot(is.numeric(`ratio`), length(`ratio`) == 1)
        self$`ratio` <- `ratio`
      }
    },
    toJSON = function() {
      StockSplitObject <- list()
      if (!is.null(self$`executionDate`)) {
        StockSplitObject[['executionDate']] <- self$`executionDate`
      }
      if (!is.null(self$`forFactor`)) {
        StockSplitObject[['forFactor']] <- self$`forFactor`
      }
      if (!is.null(self$`toFactor`)) {
        StockSplitObject[['toFactor']] <- self$`toFactor`
      }
      if (!is.null(self$`ratio`)) {
        StockSplitObject[['ratio']] <- self$`ratio`
      }

      StockSplitObject
    },
    fromJSON = function(StockSplitJson) {
      StockSplitObject <- jsonlite::fromJSON(StockSplitJson)
      if (!is.null(StockSplitObject$`executionDate`)) {
        self$`executionDate` <- StockSplitObject$`executionDate`
      }
      if (!is.null(StockSplitObject$`forFactor`)) {
        self$`forFactor` <- StockSplitObject$`forFactor`
      }
      if (!is.null(StockSplitObject$`toFactor`)) {
        self$`toFactor` <- StockSplitObject$`toFactor`
      }
      if (!is.null(StockSplitObject$`ratio`)) {
        self$`ratio` <- StockSplitObject$`ratio`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "executionDate": %s,
           "forFactor": %d,
           "toFactor": %d,
           "ratio": %d
        }',
        self$`executionDate`,
        self$`forFactor`,
        self$`toFactor`,
        self$`ratio`
      )
    },
    fromJSONString = function(StockSplitJson) {
      StockSplitObject <- jsonlite::fromJSON(StockSplitJson)
      self$`executionDate` <- StockSplitObject$`executionDate`
      self$`forFactor` <- StockSplitObject$`forFactor`
      self$`toFactor` <- StockSplitObject$`toFactor`
      self$`ratio` <- StockSplitObject$`ratio`
    }
  )
)
