# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Transaction Class
#'
#' @field date 
#' @field name 
#' @field type 
#' @field amount 
#' @field price 
#' @field documentLink 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Transaction <- R6::R6Class(
  'Transaction',
  public = list(
    `date` = NULL,
    `name` = NULL,
    `type` = NULL,
    `amount` = NULL,
    `price` = NULL,
    `documentLink` = NULL,
    initialize = function(`date`, `name`, `type`, `amount`, `price`, `documentLink`){
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!missing(`amount`)) {
        stopifnot(is.numeric(`amount`), length(`amount`) == 1)
        self$`amount` <- `amount`
      }
      if (!missing(`price`)) {
        stopifnot(is.numeric(`price`), length(`price`) == 1)
        self$`price` <- `price`
      }
      if (!missing(`documentLink`)) {
        stopifnot(is.character(`documentLink`), length(`documentLink`) == 1)
        self$`documentLink` <- `documentLink`
      }
    },
    toJSON = function() {
      TransactionObject <- list()
      if (!is.null(self$`date`)) {
        TransactionObject[['date']] <- self$`date`
      }
      if (!is.null(self$`name`)) {
        TransactionObject[['name']] <- self$`name`
      }
      if (!is.null(self$`type`)) {
        TransactionObject[['type']] <- self$`type`$toJSON()
      }
      if (!is.null(self$`amount`)) {
        TransactionObject[['amount']] <- self$`amount`
      }
      if (!is.null(self$`price`)) {
        TransactionObject[['price']] <- self$`price`
      }
      if (!is.null(self$`documentLink`)) {
        TransactionObject[['documentLink']] <- self$`documentLink`
      }

      TransactionObject
    },
    fromJSON = function(TransactionJson) {
      TransactionObject <- jsonlite::fromJSON(TransactionJson)
      if (!is.null(TransactionObject$`date`)) {
        self$`date` <- TransactionObject$`date`
      }
      if (!is.null(TransactionObject$`name`)) {
        self$`name` <- TransactionObject$`name`
      }
      if (!is.null(TransactionObject$`type`)) {
        typeObject <- TransactionType$new()
        typeObject$fromJSON(jsonlite::toJSON(TransactionObject$type, auto_unbox = TRUE))
        self$`type` <- typeObject
      }
      if (!is.null(TransactionObject$`amount`)) {
        self$`amount` <- TransactionObject$`amount`
      }
      if (!is.null(TransactionObject$`price`)) {
        self$`price` <- TransactionObject$`price`
      }
      if (!is.null(TransactionObject$`documentLink`)) {
        self$`documentLink` <- TransactionObject$`documentLink`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "date": %s,
           "name": %s,
           "type": %s,
           "amount": %d,
           "price": %d,
           "documentLink": %s
        }',
        self$`date`,
        self$`name`,
        self$`type`$toJSON(),
        self$`amount`,
        self$`price`,
        self$`documentLink`
      )
    },
    fromJSONString = function(TransactionJson) {
      TransactionObject <- jsonlite::fromJSON(TransactionJson)
      self$`date` <- TransactionObject$`date`
      self$`name` <- TransactionObject$`name`
      TransactionTypeObject <- TransactionType$new()
      self$`type` <- TransactionTypeObject$fromJSON(jsonlite::toJSON(TransactionObject$type, auto_unbox = TRUE))
      self$`amount` <- TransactionObject$`amount`
      self$`price` <- TransactionObject$`price`
      self$`documentLink` <- TransactionObject$`documentLink`
    }
  )
)
